# Limpieza de dtos de Macrofauna

In [37]:
import numpy as np 
import pandas as pd
import re 
import datetime
import traceback as tb
import sys
import math
import unicodedata
from datetime import time

#df_macrofauna = pd.read_excel(r'C:\Users\Felipe Abarzúa\Desktop\DATA_AMBIENTALES\Proyecto Seguimiento Ambiental\2019_P656115\2_BD_MACROFAUNA_2019.xlsx' , sheet_name= 'BD_Macrofauna2019')

In [ ]:
df_macrofauna = pd.read_excel(r'C:\Users\Felipe Abarzúa\Desktop\DATA_AMBIENTALES\Proyecto Seguimiento Ambiental\2019_P656115\2_BD_MACROFAUNA_2019.xlsx' , sheet_name= 'BD_Macrofauna2019')


df_macrofauna

,Nombre del Proyecto:,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICULTURA EN CHILE Y SU EFECTO EN LOS ECOSISTEMAS DE EMPLAZAMIENTO 2019 -2020,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
0,Codigo del Proyecto:,656-115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Etapa Proyecto:,Objetivo 1. Actividad 2. Muestreos y Analisis ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Jefe Proyecto,Gastón Vidal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Institucion:,INSTITUTO DE FOMENTO PESQUERO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Nombre Sector:,"Atacama (Caldera-Bahia Inglesa), Coquimbo (Ton...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3206,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,Objetivo 1. Actividad 2. Muestreos y Analisis ...,GASTON VIDAL,INSTITUTO DE FOMENTO PESQUERO,Natales,XII,Macrofauna,2019-08-11 00:00:00,2019-08-11 00:00:00,...,11,0.0004,110,0.004,Annelida,Polychaeta,Dorvilleidae,Pettiboneia wui,NaN,NaN
3207,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,Objetivo 1. Actividad 2. Muestreos y Analisis ...,GASTON VIDAL,INSTITUTO DE FOMENTO PESQUERO,Natales,XII,Macrofauna,2019-08-11 00:00:00,2019-08-11 00:00:00,...,29,0.0011,290,0.011,Arthropoda,Copepoda,Copepoda,Ciclopoideo,NaN,NaN
3208,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,Objetivo 1. Actividad 2. Muestreos y Analisis ...,GASTON VIDAL,INSTITUTO DE FOMENTO PESQUERO,Natales,XII,Macrofauna,2019-08-11 00:00:00,2019-08-11 00:00:00,...,1,0.0002,10,0.002,Arthropoda,Tanaidacea,Tanaidacea,Tanaidacea,NaN,NaN
3209,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,Objetivo 1. Actividad 2. Muestreos y Analisis ...,GASTON VIDAL,INSTITUTO DE FOMENTO PESQUERO,Natales,XII,Macrofauna,2019-08-11 00:00:00,2019-08-11 00:00:00,...,5,0.0004,50,0.004,Annelida,Polychaeta,Cirratulidae,Apelochaeta sp.,NaN,NaN
3210,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,Objetivo 1. Actividad 2. Muestreos y Analisis ...,GASTON VIDAL,INSTITUTO DE FOMENTO PESQUERO,Natales,XII,Macrofauna,2019-08-11 00:00:00,2019-08-11 00:00:00,...,1,0.0061,10,0.061,Mollusca,Bivalvia,Malletidae,Malletia magellanica,NaN,NaN

In [ ]:
def limpieza_macrofauna(df):

    try:

        #Eliminamos las fil as innecesarias
        df =  df.iloc[13: , :]

        #Reiniciamos los indices del dataframe y eliminamos la columna de index 
        df =  df.reset_index(drop = True)

        #Creamos una copia del dataframe
        df_macrofauna_copy = df.copy()

        #Dejamos la primera fila como columna
        df_macrofauna_copy.columns = df_macrofauna_copy.iloc[0]

        #Eliminamos la primera fila del dataset 
        df_macrofauna_copy = df_macrofauna_copy.iloc[1: , :]

        #Reiniciamos los indices del dataframe
        df_macrofauna_copy = df_macrofauna_copy.reset_index(drop =  True)

        #Agregamos la columna ID 
        df_macrofauna_copy.insert(0 , 'ID' , df_macrofauna_copy.index + 1)

        #Creamos la lista de columnas 
        columnas = df_macrofauna_copy.columns.to_list()

        #Creamos las columnas fijas y las columnas variables

        columnas_fijas = ['ID', 'NOMB_PROY', 'COD_PROY', 'ETAP_PROY', 'JEFE_PROY', 'INST_PROY', 'NOM_SECTOR', 'COD_REG', 'FECHA_INI', 'FECHA_TER', 'N_ESTACION', 'LATITUD', 'LONGUITUD', 'PROF_SECT','PHYLUM', 'CLASE/ORD', 'FAMILIA', 'GEN/ESPECIE']


        columnas_variables = ['NUM_EJEMPL', 'TIPO_DRAGA', 'ABUNDANCIA', 'BIOMASA', 'IND_M2', 'GRS_M2']

        #Realizamos un melt para convertir las columnas de variables a filas 

        df_macrofauna_copy = pd.melt(df_macrofauna_copy , id_vars= columnas_fijas , value_vars=columnas_variables , var_name= 'VARIABLES_MUESTREO' , value_name= 'VALOR')


        #Renombramos los nombres de VARIABLES_MUESTREO

        df_macrofauna_copy['VARIABLES_MUESTREO'] = np.where(df_macrofauna_copy['VARIABLES_MUESTREO'] == 'ABUNDANCIA' , 'ABUNDANCIA TOTAL' , df_macrofauna_copy['VARIABLES_MUESTREO'])
        df_macrofauna_copy['VARIABLES_MUESTREO'] = np.where(df_macrofauna_copy['VARIABLES_MUESTREO'] == 'BIOMASA' , 'BIOMASA TOTAL' , df_macrofauna_copy['VARIABLES_MUESTREO'])


        #Reemplazamos todos los valores de NOMB_PROY

        df_macrofauna_copy['NOMB_PROY'] = 'ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICULTURA EN CHILE Y SU EFECTO EN LOS ECOSISTEMAS DE EMPLAZAMIENTO 2019-2020'

        #Renombramos la columnas 

        df_macrofauna_copy = df_macrofauna_copy.rename(columns = {"LONGUITUD" : "LONGITUD" , "GEN/ESPECIE" : "TAXA" , "CLASE/ORD" : "CLASE"})

        # Modificamos los formatos de las fechas a DD/MM/YYYY 24HH:MI:SS

        df_macrofauna_copy['FECHA_INI'] = df_macrofauna_copy['FECHA_INI'].dt.strftime('%d/%m/%Y %H:%M:%S')

        df_macrofauna_copy['FECHA_TER'] = df_macrofauna_copy['FECHA_TER'].dt.strftime('%d/%m/%Y %H:%M:%S')

        
         #Modificamos las columnas de Variable 

        df_macrofauna_copy['VARIABLES_MUESTREO'] = np.where(df_macrofauna_copy['VARIABLES_MUESTREO'] == 'N°_TAXA', 'NUMERO DE TAXA' , df_macrofauna_copy['VARIABLES_MUESTREO'])
        df_macrofauna_copy['VARIABLES_MUESTREO'] = np.where(df_macrofauna_copy['VARIABLES_MUESTREO'] == 'NUM_EJEMPL', 'NUMERO DE EJEMPLARES' , df_macrofauna_copy['VARIABLES_MUESTREO'])
        df_macrofauna_copy['VARIABLES_MUESTREO'] = np.where(df_macrofauna_copy['VARIABLES_MUESTREO'] == 'TIPO_DRAGA', 'TIPO DRAGA' , df_macrofauna_copy['VARIABLES_MUESTREO'])
        df_macrofauna_copy['VARIABLES_MUESTREO'] = np.where(df_macrofauna_copy['VARIABLES_MUESTREO'] == 'TIPO_DRAGA', 'TIPO DRAGA' , df_macrofauna_copy['VARIABLES_MUESTREO'])
        df_macrofauna_copy['VARIABLES_MUESTREO'] = np.where(df_macrofauna_copy['VARIABLES_MUESTREO'] == 'ABUNDANCIA' , 'ABUNDANCIA TOTAL' , df_macrofauna_copy['VARIABLES_MUESTREO'])
        df_macrofauna_copy['VARIABLES_MUESTREO'] = np.where(df_macrofauna_copy['VARIABLES_MUESTREO'] == 'BIOMASA' , 'BIOMASA TOTAL' , df_macrofauna_copy['VARIABLES_MUESTREO'])



        return df_macrofauna_copy , columnas

    except Exception as e:
        print(f"Ocurrió un error en la función limpieza_ctd: {e}")
        ex = sys.exc_info()[2]
        print("Error en el archivo : " + str(ex.tb_frame) + " En la linea : " + str(ex.tb_lineno))
        
        return None #O devuelve un valor que indique el fallo

In [83]:
df_macrofauna_copy , columnas = limpieza_macrofauna(df_macrofauna)

In [64]:
df_macrofauna_copy

,ID,NOMB_PROY,COD_PROY,ETAP_PROY,JEFE_PROY,INST_PROY,NOM_SECTOR,COD_REG,FECHA_INI,FECHA_TER,N_ESTACION,LATITUD,LONGITUD,PROF_SECT,PHYLUM,CLASE,FAMILIA,TAXA,VARIABLES_MUESTREO,VALOR
0,1,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,Objetivo 1. Actividad 2. Muestreos y Analisis ...,GASTON VIDAL,INSTITUTO DE FOMENTO PESQUERO,Atacama,III,11/04/2019 00:00:00,11/04/2019 00:00:00,2,-27.107,-70.864889,21,Mollusca,Gastropoda,Capulidae,Capulus compressus,NUM_EJEMPL,4540
1,2,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,Objetivo 1. Actividad 2. Muestreos y Analisis ...,GASTON VIDAL,INSTITUTO DE FOMENTO PESQUERO,Atacama,III,11/04/2019 00:00:00,11/04/2019 00:00:00,2,-27.107,-70.864889,21,Mollusca,Gastropoda,Collumbellidae,Salitra radwini,NUM_EJEMPL,4540
2,3,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,Objetivo 1. Actividad 2. Muestreos y Analisis ...,GASTON VIDAL,INSTITUTO DE FOMENTO PESQUERO,Atacama,III,11/04/2019 00:00:00,11/04/2019 00:00:00,2,-27.107,-70.864889,21,Mollusca,Gastropoda,Nassaridae,Nassarius coppingeri,NUM_EJEMPL,4540
3,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,Objetivo 1. Actividad 2. Muestreos y Analisis ...,GASTON VIDAL,INSTITUTO DE FOMENTO PESQUERO,Atacama,III,11/04/2019 00:00:00,11/04/2019 00:00:00,2,-27.107,-70.864889,21,Mollusca,Bivalvia,Nuculidae,Linucula pisum,NUM_EJEMPL,4540
4,5,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,Objetivo 1. Actividad 2. Muestreos y Analisis ...,GASTON VIDAL,INSTITUTO DE FOMENTO PESQUERO,Atacama,III,11/04/2019 00:00:00,11/04/2019 00:00:00,2,-27.107,-70.864889,21,Mollusca,Bivalvia,Solemyidae,Acharax patagonica,NUM_EJEMPL,4540
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19177,3193,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,Objetivo 1. Actividad 2. Muestreos y Analisis ...,GASTON VIDAL,INSTITUTO DE FOMENTO PESQUERO,Natales,XII,11/08/2019 00:00:00,11/08/2019 00:00:00,14,-52.077583,-72.660444,25,Annelida,Polychaeta,Dorvilleidae,Pettiboneia wui,GRS_M2,0.004
19178,3194,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,Objetivo 1. Actividad 2. Muestreos y Analisis ...,GASTON VIDAL,INSTITUTO DE FOMENTO PESQUERO,Natales,XII,11/08/2019 00:00:00,11/08/2019 00:00:00,14,-52.077583,-72.660444,25,Arthropoda,Copepoda,Copepoda,Ciclopoideo,GRS_M2,0.011
19179,3195,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,Objetivo 1. Actividad 2. Muestreos y Analisis ...,GASTON VIDAL,INSTITUTO DE FOMENTO PESQUERO,Natales,XII,11/08/2019 00:00:00,11/08/2019 00:00:00,14,-52.077583,-72.660444,25,Arthropoda,Tanaidacea,Tanaidacea,Tanaidacea,GRS_M2,0.002
19180,3196,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,Objetivo 1. Actividad 2. Muestreos y Analisis ...,GASTON VIDAL,INSTITUTO DE FOMENTO PESQUERO,Natales,XII,11/08/2019 00:00:00,11/08/2019 00:00:00,14,-52.077583,-72.660444,25,Annelida,Polychaeta,Cirratulidae,Apelochaeta sp.,GRS_M2,0.004
19181,3197,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,Objetivo 1. Actividad 2. Muestreos y Analisis ...,GASTON VIDAL,INSTITUTO DE FOMENTO PESQUERO,Natales,XII,11/08/2019 00:00:00,11/08/2019 00:00:00,14,-52.077583,-72.660444,25,Mollusca,Bivalvia,Malletidae,Malletia magellanica,GRS_M2,0.061

In [65]:
df_macrofauna_copy.to_csv('output/2019/AMBIENTALES_MACROFAUNA_2019.csv' , index=False)

# Limpieza de datos de CTD y CTD COMPU

In [3]:
df_ctd = pd.read_excel(r'C:\Users\Felipe Abarzúa\Desktop\DATA_AMBIENTALES\Proyecto Seguimiento Ambiental\2019_P656115\3_BD_CTD_SEGUIMIENTO2019.xlsx' , sheet_name= 'Base de Datos CTD2019 IFOP')

#df_ctd_compu = pd.read_excel(r'C:\Users\felipe.abarzua\Desktop\DATA_AMBIENTALES\Proyecto Seguimiento Ambiental\2019_P656115\6_BD_CTD_COMPU_2019.xlsx' , sheet_name='Sept_nov_COMPU')

In [ ]:
df_ctd

,Nombre del Proyecto:,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICULTURA EN CHILE Y SU EFECTO EN LOS ECOSISTEMAS DE EMPLAZAMIENTO 2019 -2020,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27
0,Codigo del Proyecto:,656-115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Fecha inicio del muestreo:,9 mayo de 2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Fecha fin del muestreo:,26 de junio 2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Equipos de medición:,CTD SeaBird SBE19plus// SerialNumber 01907566/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Botella Niskin 5 litros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-06-20 00:00:00,2019-06-20 00:00:00,CTD SeaBird SBE19plus,-46.676652,-73.9255,127,135.9,6.1698,...,NaN,NaN,NaN,NaN,XI,31,NaN,31,14:56:00,NaN
6429,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-06-20 00:00:00,2019-06-20 00:00:00,CTD SeaBird SBE19plus,-46.676652,-73.9255,128,135.9,6.1781,...,NaN,NaN,NaN,NaN,XI,31,NaN,31,14:56:00,NaN
6430,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-06-20 00:00:00,2019-06-20 00:00:00,CTD SeaBird SBE19plus,-46.676652,-73.9255,129,135.9,6.1842,...,NaN,NaN,NaN,NaN,XI,31,NaN,31,14:56:00,NaN
6431,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-06-20 00:00:00,2019-06-20 00:00:00,CTD SeaBird SBE19plus,-46.676652,-73.9255,130,135.9,6.1917,...,NaN,NaN,NaN,NaN,XI,31,NaN,31,14:56:00,NaN
6432,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-06-20 00:00:00,2019-06-20 00:00:00,CTD SeaBird SBE19plus,-46.676652,-73.9255,131,135.9,6.1961,...,NaN,NaN,NaN,NaN,XI,31,NaN,31,14:56:00,NaN

In [5]:
def limpieza_ctd(df):
    
    try:
        # Eliminamos las filas innecesarias
        df = df.iloc[18:, :]

        # Reiniciamos los indices
        df = df.reset_index(drop=True)

        # Creamos una copia del dataset
        df_ctd_copy = df.copy()

        # Dejamos la primera fila como columna
        df_ctd_copy.columns = df_ctd_copy.iloc[0]

        # Eliminamos la primera fila
        df_ctd_copy = df_ctd_copy.iloc[1:, :]

        # Reiniciamos los indices
        df_ctd_copy = df_ctd_copy.reset_index(drop=True)

        # Agregamos una columna de ID para identificar los datos antes de realizar el Melt
        df_ctd_copy.insert(0, 'ID', df_ctd_copy.index + 1)

        # Renombramos las columnas
        df_ctd_copy = df_ctd_copy.rename(columns={  'ESTACION' : 'N_ESTACION' ,  'LONGUITUD': 'LONGITUD', 'TEMPERATUR': 'TEMPERATURA', 'HORA_DATO  ': 'HORA_DATO', 'OXIG_ml/L': 'OXIGENO_DIS_ML/L', 'OXIG_mg/L': 'OXIGENO_DIS_MG/L', 'OXIG_%sat': 'OXIGENO_DIS_SAT', 'OX_umol/kg': 'OXIGENO_DIS_UMOLKG', 'FLUORESCEN': 'FLUORESCENCIA'})

        # Creamos las columnas fijas y columnas de variables
        columnas_fijas = ['ID', 'NOMB_PROY', 'COD_PROY', 'FECHA_INI', 'FECHA_TER', 'EQUIPO', 'LATITUD', 'LONGITUD', 'PROF_EQ', 'PROF_SECT', 'COD_REG', 'OBSERV', 'SHAPE', 'N_ESTACION', 'HORA_DATO']
        columnas_variables = ['TEMPERATURA', 'OXIGENO_DIS_ML/L', 'OXIGENO_DIS_MG/L', 'OXIGENO_DIS_SAT', 'OXIGENO_DIS_UMOLKG', 'FLUORESCENCIA', 'SALINIDAD', 'DENSIDAD', 'CLOROFILA', 'FEOPIGMEN', 'NITRATO', 'FOSFATO', 'SILICATO']

        """
        Realizamos un melt para convertir las columnas de Variables a filas

            Necesita:
            1. Dataframe a cambiar
            2. id_vars : Lista o Tupla de las columnas Fijas
            3. value_vars : Lista o Tupla de las columnas de Variables
            4. var_name : Nombre de la nueva columna de las Variables
            5. value_name : Nombre de la columna con los valores de la columna de Variables

        """

        df_ctd_copy = pd.melt(df_ctd_copy, id_vars=columnas_fijas, value_vars=columnas_variables, var_name='VARIABLE', value_name='VALOR')

        # Creamos una columna de fecha

        # df_ctd_copy.insert(10 , 'FECHA_DATO' , df_ctd_copy.apply(lambda row: datetime.datetime(row['FECHA_TER']), axis=1) )

        # Convertimos la HORA_DATO a string

        df_ctd_copy['HORA_DATO'] = df_ctd_copy['HORA_DATO'].astype(str)

        # Remplazamos los 'nan'

        df_ctd_copy['HORA_DATO'] = np.where(df_ctd_copy['HORA_DATO'] == 'nan', '00:00:00', df_ctd_copy['HORA_DATO'])

        # Creamos un campo de FECHA_DATO
        df_ctd_copy['FECHA_DATO'] = df_ctd_copy['FECHA_TER'].dt.strftime('%d/%m/%Y') + ' ' + df_ctd_copy['HORA_DATO']

        # Realizamos un formateo a los campos de fechas
        df_ctd_copy['FECHA_INI'] = pd.to_datetime(df_ctd_copy['FECHA_INI'], format='%d/%m/%Y %H:%M:%S', errors='coerce')
        df_ctd_copy['FECHA_TER'] = pd.to_datetime(df_ctd_copy['FECHA_TER'], format='%d/%m/%Y %H:%M:%S', errors='coerce')
        df_ctd_copy['FECHA_DATO'] = pd.to_datetime(df_ctd_copy['FECHA_DATO'], format='%d/%m/%Y %H:%M:%S', errors='coerce')

        #



    
        return df_ctd_copy, columnas_fijas, columnas_variables

    except Exception as e:
        print(f"Ocurrió un error en la función limpieza_ctd: {e}")
        ex = sys.exc_info()[2]
        print("Error en el archivo : " + str(ex.tb_frame) + " En la linea : " + str(ex.tb_lineno))
        
        return None, None, None  # O devuelve un valor que indique el fallo

In [6]:
df_ctd_copy , columnas_fijas , columnas_variables = limpieza_ctd(df_ctd)

In [7]:
df_ctd_copy

,ID,NOMB_PROY,COD_PROY,FECHA_INI,FECHA_TER,EQUIPO,LATITUD,LONGITUD,PROF_EQ,PROF_SECT,COD_REG,OBSERV,SHAPE,N_ESTACION,HORA_DATO,VARIABLE,VALOR,FECHA_DATO
0,1,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-05-11,2019-05-11,CTD SeaBird SBE19plus,-41.584401,-72.338603,1,134,X,1,NaN,1,09:05:00,TEMPERATURA,12.2883,2019-05-11 09:05:00
1,2,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-05-11,2019-05-11,CTD SeaBird SBE19plus,-41.584401,-72.338603,2,134,X,1,NaN,1,09:05:00,TEMPERATURA,12.0498,2019-05-11 09:05:00
2,3,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-05-11,2019-05-11,CTD SeaBird SBE19plus,-41.584401,-72.338603,3,134,X,1,NaN,1,09:05:00,TEMPERATURA,11.7416,2019-05-11 09:05:00
3,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-05-11,2019-05-11,CTD SeaBird SBE19plus,-41.584401,-72.338603,4,134,X,1,NaN,1,09:05:00,TEMPERATURA,11.6439,2019-05-11 09:05:00
4,5,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-05-11,2019-05-11,CTD SeaBird SBE19plus,-41.584401,-72.338603,5,134,X,1,NaN,1,09:05:00,TEMPERATURA,11.5449,2019-05-11 09:05:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83377,6410,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-06-20,2019-06-20,CTD SeaBird SBE19plus,-46.676652,-73.9255,127,135.9,XI,31,NaN,31,14:56:00,SILICATO,NaN,2019-06-20 14:56:00
83378,6411,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-06-20,2019-06-20,CTD SeaBird SBE19plus,-46.676652,-73.9255,128,135.9,XI,31,NaN,31,14:56:00,SILICATO,NaN,2019-06-20 14:56:00
83379,6412,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-06-20,2019-06-20,CTD SeaBird SBE19plus,-46.676652,-73.9255,129,135.9,XI,31,NaN,31,14:56:00,SILICATO,NaN,2019-06-20 14:56:00
83380,6413,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-06-20,2019-06-20,CTD SeaBird SBE19plus,-46.676652,-73.9255,130,135.9,XI,31,NaN,31,14:56:00,SILICATO,NaN,2019-06-20 14:56:00
83381,6414,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-06-20,2019-06-20,CTD SeaBird SBE19plus,-46.676652,-73.9255,131,135.9,XI,31,NaN,31,14:56:00,SILICATO,NaN,2019-06-20 14:56:00

In [8]:
df_latitud_longitud = df_ctd_copy[['LATITUD' , 'LONGITUD']].drop_duplicates()

In [9]:
df_latitud_longitud

        LATITUD   LONGITUD
0    -41.584401 -72.338603
97   -41.691478 -72.417579
310  -41.701238 -72.672367
555  -41.747814 -72.862254
862  -41.850981 -72.955801
1144 -42.049798 -72.813589
1383 -42.331447 -72.904902
1594 -42.461262 -73.090724
1943 -42.614495 -72.967202
2160 -42.608094 -73.161339
2326 -42.901452 -72.943776
2456 -43.172371 -72.968933
2652 -43.529964 -73.155924
2817    -43.811    -73.144
3019    -44.102    -73.367
3140 -44.291389 -73.061952
3254 -44.411049 -72.876181
3524 -44.535254 -72.678194
3786 -44.797479 -72.888125
4007 -44.938535 -73.299588
4287 -45.151035 -73.651966
4534 -45.341157 -73.628639
4664    -45.388    -73.461
4962    -45.312    -73.127
5280 -45.534457 -73.532761
5550 -45.696246 -73.557658
5776    -45.933 -73.635013
5883  -46.15567 -73.669804
5976    -46.317    -73.636
6171 -46.427264 -73.780306
6283 -46.676652   -73.9255

In [ ]:
def limpieza_ctd_compu(df):
    
    try:
        # Eliminamos las filas innecesarias
        df = df.iloc[11:, :]

        # Reiniciamos los indices
        df = df.reset_index(drop=True)

        # Creamos una copia del dataset
        df_ctd_copy = df.copy()

        # Dejamos la primera fila como columna
        df_ctd_copy.columns = df_ctd_copy.iloc[0]

        # Eliminamos la primera fila
        df_ctd_copy = df_ctd_copy.iloc[1:, :]

        # Reiniciamos los indices
        df_ctd_copy = df_ctd_copy.reset_index(drop=True)

        # Agregamos una columna de ID para identificar los datos antes de realizar el Melt
        df_ctd_copy.insert(0, 'ID', df_ctd_copy.index + 1)

        # Renombramos las columnas
        df_ctd_copy = df_ctd_copy.rename(columns={ 'LONGUITUD': 'LONGITUD', 'TEMPERATU': 'TEMPERATURA', 'HORA DATO': 'HORA_DATO', 'OXIGE_ml/L': 'OXIGENO_DIS_ML/L', 'OXIGE_mg/L': 'OXIGENO_DIS_MG/L', 'OXIGE_%sat': 'OXIGENO_DIS_SAT', 'OX_umol/kg': 'OXIGENO_DIS_UMOLKG', 'FLUORESCEN': 'FLUORESCENCIA'})

        # Creamos las columnas fijas y columnas de variables
        columnas_fijas = ['ID', 'NOMB_PROY', 'COD_PROY', 'FECHA_INI', 'FECHA_TER', 'EQUIPO', 'LATITUD', 'LONGITUD', 'PROF_EQU', 'PROF_SECT', 'COD_REG', 'HORA_DATO' , 'ESTACION']
        columnas_variables = ['TEMPERATURA','OXIGENO_DIS_ML/L', 'OXIGENO_DIS_MG/L', 'OXIGENO_DIS_SAT','OXIGENO_DIS_UMOLKG', 'FLUORESCENCIA', 'SALINIDAD', 'ACIDEZ(pH)','TURBID_NTU']

        """
        Realizamos un melt para convertir las columnas de Variables a filas

            Necesita:
            1. Dataframe a cambiar
            2. id_vars : Lista o Tupla de las columnas Fijas
            3. value_vars : Lista o Tupla de las columnas de Variables
            4. var_name : Nombre de la nueva columna de las Variables
            5. value_name : Nombre de la columna con los valores de la columna de Variables

        """

        df_ctd_copy = pd.melt(df_ctd_copy, id_vars=columnas_fijas, value_vars=columnas_variables, var_name='VARIABLE', value_name='VALOR')

        # Convertimos la HORA_DATO a string

        df_ctd_copy['HORA_DATO'] = df_ctd_copy['HORA_DATO'].astype(str)

        # Remplazamos los 'nan' por 00:00:00

        df_ctd_copy['HORA_DATO'] = np.where(df_ctd_copy['HORA_DATO'] == 'nan', '00:00:00', df_ctd_copy['HORA_DATO'])

        # Creamos un campo de FECHA_DATO
        df_ctd_copy['FECHA_DATO'] = df_ctd_copy['FECHA_TER'].dt.strftime('%d/%m/%Y') + ' ' + df_ctd_copy['HORA_DATO']

        # Realizamos un formateo a los campos de fechas
        df_ctd_copy['FECHA_INI'] = pd.to_datetime(df_ctd_copy['FECHA_INI'], format='%d/%m/%Y %H:%M:%S', errors='coerce')
        df_ctd_copy['FECHA_TER'] = pd.to_datetime(df_ctd_copy['FECHA_TER'], format='%d/%m/%Y %H:%M:%S', errors='coerce')
        df_ctd_copy['FECHA_DATO'] = pd.to_datetime(df_ctd_copy['FECHA_DATO'], format='%d/%m/%Y %H:%M:%S', errors='coerce')


        # Cambiamos los NOMB_PROY ,  
        df_ctd_copy['NOMB_PROY'] = 'ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICULTURA EN CHILE Y SU EFECTO EN LOS ECOSISTEMAS DE EMPLAZAMIENTO 2019-2020'

        #Creamos la columna de N_ESTACION obteneiendo los numeros de la columna ESTACION
        df_ctd_copy['N_ESTACION'] = df_ctd_copy['ESTACION'].str.extract(r'(\d+)')

        #Dejamos la columna N_ESTACION como entero 

        df_ctd_copy['N_ESTACION'] = df_ctd_copy['N_ESTACION'].astype(int)



        return df_ctd_copy, columnas_fijas, columnas_variables

    except Exception as e:
        print(f"Ocurrió un error en la función limpieza_ctd: {e}")
        ex = sys.exc_info()[2]
        print("Error en el archivo : " + str(ex.tb_frame) + " En la linea : " + str(ex.tb_lineno))
        
        return None, None, None  # O devuelve un valor que indique el fallo

In [ ]:
df_ctd_compu_copy , columnas_fijas , columnas_variables = limpieza_ctd_compu(df_ctd_compu)

In [ ]:
df_ctd_compu_copy

,ID,NOMB_PROY,COD_PROY,FECHA_INI,FECHA_TER,EQUIPO,LATITUD,LONGITUD,PROF_EQU,PROF_SECT,COD_REG,HORA_DATO,ESTACION,VARIABLE,VALOR,FECHA_DATO,N_ESTACION
0,1,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-09-10,2019-09-10,CTD SeaBird SBE19plus,-42.8624,-73.7122,1,31,X,14:38:00,E2,TEMPERATURA,10.064,2019-09-10 14:38:00,2
1,2,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-09-10,2019-09-10,CTD SeaBird SBE19plus,-42.8624,-73.7122,2,31,X,14:38:00,E2,TEMPERATURA,10.414,2019-09-10 14:38:00,2
2,3,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-09-10,2019-09-10,CTD SeaBird SBE19plus,-42.8624,-73.7122,3,31,X,14:38:00,E2,TEMPERATURA,10.585,2019-09-10 14:38:00,2
3,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-09-10,2019-09-10,CTD SeaBird SBE19plus,-42.8624,-73.7122,4,31,X,14:38:00,E2,TEMPERATURA,10.323,2019-09-10 14:38:00,2
4,5,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-09-10,2019-09-10,CTD SeaBird SBE19plus,-42.8624,-73.7122,5,31,X,14:38:00,E2,TEMPERATURA,10.317,2019-09-10 14:38:00,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18274,2027,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-11-07,2019-11-07,CTD SeaBird SBE19plus,-43.058,-73.393,181,185,X,09:30:00,E27,TURBID_NTU,0.285,2019-11-07 09:30:00,27
18275,2028,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-11-07,2019-11-07,CTD SeaBird SBE19plus,-43.058,-73.393,182,185,X,09:30:00,E27,TURBID_NTU,0.292,2019-11-07 09:30:00,27
18276,2029,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-11-07,2019-11-07,CTD SeaBird SBE19plus,-43.058,-73.393,183,185,X,09:30:00,E27,TURBID_NTU,0.32,2019-11-07 09:30:00,27
18277,2030,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-11-07,2019-11-07,CTD SeaBird SBE19plus,-43.058,-73.393,184,185,X,09:30:00,E27,TURBID_NTU,0.32,2019-11-07 09:30:00,27
18278,2031,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-11-07,2019-11-07,CTD SeaBird SBE19plus,-43.058,-73.393,185,185,X,09:30:00,E27,TURBID_NTU,0.307,2019-11-07 09:30:00,27

In [ ]:
df_ctd_compu_copy['VARIABLE'].unique()

array(['TEMPERATURA', 'OXIGENO_DIS_ML/L', 'OXIGENO_DIS_MG/L',
       'OXIGENO_DIS_SAT', 'OXIGENO_DIS_UMOLKG', 'FLUORESCENCIA',
       'SALINIDAD', 'ACIDEZ(pH)', 'TURBID_NTU'], dtype=object)

In [ ]:
df_ctd_compu_copy

,ID,NOMB_PROY,COD_PROY,FECHA_INI,FECHA_TER,EQUIPO,LATITUD,LONGITUD,PROF_EQU,PROF_SECT,COD_REG,HORA_DATO,ESTACION,VARIABLE,VALOR,FECHA_DATO,N_ESTACION
0,1,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-09-10,2019-09-10,CTD SeaBird SBE19plus,-42.8624,-73.7122,1,31,X,14:38:00,E2,TEMPERATURA,10.064,2019-09-10 14:38:00,2
1,2,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-09-10,2019-09-10,CTD SeaBird SBE19plus,-42.8624,-73.7122,2,31,X,14:38:00,E2,TEMPERATURA,10.414,2019-09-10 14:38:00,2
2,3,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-09-10,2019-09-10,CTD SeaBird SBE19plus,-42.8624,-73.7122,3,31,X,14:38:00,E2,TEMPERATURA,10.585,2019-09-10 14:38:00,2
3,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-09-10,2019-09-10,CTD SeaBird SBE19plus,-42.8624,-73.7122,4,31,X,14:38:00,E2,TEMPERATURA,10.323,2019-09-10 14:38:00,2
4,5,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-09-10,2019-09-10,CTD SeaBird SBE19plus,-42.8624,-73.7122,5,31,X,14:38:00,E2,TEMPERATURA,10.317,2019-09-10 14:38:00,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18274,2027,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-11-07,2019-11-07,CTD SeaBird SBE19plus,-43.058,-73.393,181,185,X,09:30:00,E27,TURBID_NTU,0.285,2019-11-07 09:30:00,27
18275,2028,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-11-07,2019-11-07,CTD SeaBird SBE19plus,-43.058,-73.393,182,185,X,09:30:00,E27,TURBID_NTU,0.292,2019-11-07 09:30:00,27
18276,2029,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-11-07,2019-11-07,CTD SeaBird SBE19plus,-43.058,-73.393,183,185,X,09:30:00,E27,TURBID_NTU,0.32,2019-11-07 09:30:00,27
18277,2030,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-11-07,2019-11-07,CTD SeaBird SBE19plus,-43.058,-73.393,184,185,X,09:30:00,E27,TURBID_NTU,0.32,2019-11-07 09:30:00,27
18278,2031,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-11-07,2019-11-07,CTD SeaBird SBE19plus,-43.058,-73.393,185,185,X,09:30:00,E27,TURBID_NTU,0.307,2019-11-07 09:30:00,27

# Limpieza de datos CTD COMAU

In [ ]:
df_ctd_comau = pd.read_excel(r'C:\Users\felipe.abarzua\Desktop\DATA_AMBIENTALES\Proyecto Seguimiento Ambiental\2019_P656115\7_BD_CTD_COMAU_2019.xlsx' , sheet_name='COMAU_JUN_AGOS_DIC_FEB_2019-20')

In [ ]:
df_ctd_comau

,Nombre del Proyecto:,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICULTURA EN CHILE Y SU EFECTO EN LOS ECOSISTEMAS DE EMPLAZAMIENTO 2019 -2020,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,Codigo del Proyecto:,656-115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Fecha inicio del muestreo:,2019-06-18 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Fecha fin del muestreo:,2020-02-17 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Equipos de medición:,CTD SeaBird SBE19plus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Variables:,"Temperatura (°C), oxigeno disuelto (ml/L, mg/L...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8974,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2020-02-17 00:00:00,2020-02-17 00:00:00,CTD SeaBird SBE19plus,-42.37614,-72.45074,294,298,11.1462,3.2715,4.6752,52.387,142.528,0.0425,32.8362,X,1,20:54:00
8975,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2020-02-17 00:00:00,2020-02-17 00:00:00,CTD SeaBird SBE19plus,-42.37614,-72.45074,295,298,11.1507,3.2648,4.6657,52.281,142.24,0.0517,32.8393,X,1,20:54:00
8976,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2020-02-17 00:00:00,2020-02-17 00:00:00,CTD SeaBird SBE19plus,-42.37614,-72.45074,296,298,11.1554,3.2614,4.6608,52.226,142.089,0.0491,32.8405,X,1,20:54:00
8977,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2020-02-17 00:00:00,2020-02-17 00:00:00,CTD SeaBird SBE19plus,-42.37614,-72.45074,297,298,11.1579,3.259,4.6575,52.189,141.988,0.058,32.8407,X,1,20:54:00
8978,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2020-02-17 00:00:00,2020-02-17 00:00:00,CTD SeaBird SBE19plus,-42.37614,-72.45074,298,298,11.1598,3.2504,4.6452,52.05,141.613,0.0484,32.8404,X,1,20:54:00

In [ ]:
def limpieza_ctd_comau(df):
    
    try:
        # Eliminamos las filas innecesarias
        df = df.iloc[12:, :]

        # Reiniciamos los indices
        df = df.reset_index(drop=True)

        # Creamos una copia del dataset
        df_ctd_copy = df.copy()

        # Dejamos la primera fila como columna
        df_ctd_copy.columns = df_ctd_copy.iloc[0]

        # Eliminamos la primera fila
        df_ctd_copy = df_ctd_copy.iloc[1:, :]

        # Reiniciamos los indices
        df_ctd_copy = df_ctd_copy.reset_index(drop=True)

        # Agregamos una columna de ID para identificar los datos antes de realizar el Melt
        df_ctd_copy.insert(0, 'ID', df_ctd_copy.index + 1)

        # Renombramos las columnas
        df_ctd_copy = df_ctd_copy.rename(columns={'LONGUITUD': 'LONGITUD', 'TEMPERATU': 'TEMPERATURA', 'HORA DATO': 'HORA_DATO', 'OXIGE_ml/L': 'OXIGENO_DIS_ML/L', 'OXIGE_mg/L': 'OXIGENO_DIS_MG/L', 'OXIGE_%sat': 'OXIGENO_DIS_SAT', 'OX_umol/kg': 'OXIGENO_DIS_UMOLKG', 'FLUORESCEN': 'FLUORESCENCIA'})

        #Creamos una lista de columnas obtenidas desde el dataframe
        columnas = df_ctd_copy.columns.to_list()

        # Creamos dos listas donde obtiene hasta los primeros 10 elementos de la lista columnas más los ultimos 3 elementos de la lista columnas
        primeros_diez_elementos = columnas[:10]
        ultimos_tres_elementos = columnas[-3:]

        # Creamos las columnas fijas 
        columnas_fijas = primeros_diez_elementos + ultimos_tres_elementos
        
        #Luego creamos la lista de columnas de variables donde parte desde el elemento 10 hasta antes de los ultimos 3 elementos
        columnas_variables = columnas[10:-3]

        """

        Realizamos un melt para convertir las columnas de Variables a filas

            Necesita:
            1. Dataframe a cambiar
            2. id_vars : Lista o Tupla de las columnas Fijas
            3. value_vars : Lista o Tupla de las columnas de Variables
            4. var_name : Nombre de la nueva columna de las Variables
            5. value_name : Nombre de la columna con los valores de la columna de Variables

        """

        df_ctd_copy = pd.melt(df_ctd_copy, id_vars=columnas_fijas, value_vars=columnas_variables, var_name='VARIABLE', value_name='VALOR')

        # Convertimos la HORA_DATO a string
        df_ctd_copy['HORA_DATO'] = df_ctd_copy['HORA_DATO'].astype(str)

        # Remplazamos los 'nan' por 00:00:00
        df_ctd_copy['HORA_DATO'] = np.where(df_ctd_copy['HORA_DATO'] == 'nan', '00:00:00', df_ctd_copy['HORA_DATO'])

        # Creamos un campo de FECHA_DATO
        df_ctd_copy['FECHA_DATO'] = df_ctd_copy['FECHA_TER'].dt.strftime('%d/%m/%Y') + ' ' + df_ctd_copy['HORA_DATO']

        # Realizamos un formateo a los campos de fechas
        df_ctd_copy['FECHA_INI'] = pd.to_datetime(df_ctd_copy['FECHA_INI'], format='%d/%m/%Y %H:%M:%S', errors='coerce')
        df_ctd_copy['FECHA_TER'] = pd.to_datetime(df_ctd_copy['FECHA_TER'], format='%d/%m/%Y %H:%M:%S', errors='coerce')
        df_ctd_copy['FECHA_DATO'] = pd.to_datetime(df_ctd_copy['FECHA_DATO'], format='%d/%m/%Y %H:%M:%S', errors='coerce')
     

        #Renombramos los NOMB_PROY

        df_ctd_copy['NOMB_PROY'] = 'ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICULTURA EN CHILE Y SU EFECTO EN LOS ECOSISTEMAS DE EMPLAZAMIENTO 2019-2020'

    
        return df_ctd_copy, columnas , columnas_fijas , columnas_variables

    except Exception as e:
        print(f"Ocurrió un error en la función limpieza_ctd: {e}")
        ex = sys.exc_info()[2]
        print("Error en el archivo : " + str(ex.tb_frame) + " En la linea : " + str(ex.tb_lineno))
        
        return None, None, None  # O devuelve un valor que indique el fallo

In [ ]:
df_ctd_comau_copy , columnas , columnas_fijas , columnas_variables = limpieza_ctd_comau(df_ctd_comau)

In [ ]:
df_ctd_comau_copy.columns

Index(['ID', 'NOMB_PROY', 'COD_PROY', 'FECHA_INI', 'FECHA_TER', 'EQUIPO',
       'LATITUD', 'LONGITUD', 'PROF_EQU', 'PROF_SECT', 'COD_REG', 'ESTACION',
       'HORA_DATO', 'VARIABLE', 'VALOR', 'FECHA_DATO'],
      dtype='object')

In [ ]:
df_ctd_comau_copy['NOMB_PROY'].unique()

array(['ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICULTURA EN CHILE Y SU EFECTO EN LOS ECOSISTEMAS DE EMPLAZAMIENTO 2019-2020'],
      dtype=object)

In [ ]:
df_ctd_comau_copy['EQUIPO'].unique()

array(['CTD SeaBird SBE19plus'], dtype=object)

# Limpieza de datos de BD_Compu_PH_RX

In [ ]:
df_compu_ph = pd.read_excel(r'C:\Users\Felipe Abarzúa\Desktop\DATA_AMBIENTALES\Proyecto Seguimiento Ambiental\2019_P656115\4_BD_COMPU_ph_Rx_T_2019.xlsx' ,  sheet_name= 'COMPU_sept_nov_feb_19')

In [ ]:
def limpieza_ph(df):
      
    try:

        #Eliminamos las filas y columnas innecesarias 

        df =  df.iloc[13: , :-2]

        #Realizamos una copia del dataset
        df_ph_copy = df.copy()

        #Reiniciamos los indices del dataframe
        df_ph_copy = df_ph_copy.reset_index(drop=True)

        #Dejamos la primera fila como columnas del dataframe
        df_ph_copy.columns = df_ph_copy.iloc[0]

        #Eliminamos la primera fila del dataframe 
        df_ph_copy = df_ph_copy.iloc[1: , :]

        #Reiniciamos los indices del dataframe
        df_ph_copy = df_ph_copy.reset_index(drop=True)

        #Renombramos las columnas del dataframe 
        df_ph_copy = df_ph_copy.rename(columns={'LONGUITUD' : 'LONGITUD'})

        #Creamos una columna ID en la primera columna del dataframe
        df_ph_copy.insert(0 , 'ID' , df_ph_copy.index + 1)

        #Creamos la lista de columnas
        columnas = df_ph_copy.columns.to_list()

        #Creamos las columnas fijas y las columnas de variables

        columnas_fijas = columnas[:16]
        columnas_variables = columnas[16:]

        """
              Realizamos un melt para convertir las columnas de Variables a filas

            Necesita:
            1. Dataframe a cambiar
            2. id_vars : Lista o Tupla de las columnas Fijas
            3. value_vars : Lista o Tupla de las columnas de Variables
            4. var_name : Nombre de la nueva columna de las Variables
            5. value_name : Nombre de la columna con los valores de la columna de Variables


        """

        df_ph_copy = pd.melt(df_ph_copy , id_vars=columnas_fijas , value_vars=columnas_variables , var_name= "COLUMNA_VARIABLES" , value_name= "VALOR" )


        #Cambiamos el tipo de dato de la columna FECHA_INICIO a string

        df_ph_copy['FECHA_INI'] = df_ph_copy['FECHA_INI'].astype(str)
        df_ph_copy['HORA_INI'] = df_ph_copy['HORA_INI'].astype(str)

        #Cambiamos los nan de la columna HORA_INI a 00:00:00
        
        df_ph_copy['HORA_INI'] = np.where(df_ph_copy['HORA_INI'] == 'nan' , '00:00:00' , df_ph_copy['HORA_INI'])

        #Creamos una columna de FECHA_INICIO y FECHA_TERMINO

        df_ph_copy['FECHA_INICIO'] = pd.to_datetime(df_ph_copy['FECHA_INI'] + ' ' + df_ph_copy['HORA_INI'], format='%Y-%m-%d %H:%M:%S', errors='coerce')
       
        #Cambiamos el formato de la fecha
        df_ph_copy['FECHA_INICIO'] = df_ph_copy['FECHA_INICIO'].dt.strftime('%d/%m/%Y %H:%M:%S')


        #
        df_ph_copy['NOMB_PROY'] = 'ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICULTURA EN CHILE Y SU EFECTO EN LOS ECOSISTEMAS DE EMPLAZAMIENTO 2019-2020'

          #Dejamos la columna de variables en mayuscula 

        df_ph_copy['COLUMNA_VARIABLES'] = df_ph_copy['COLUMNA_VARIABLES'].str.upper()

        #Reemplazamos los valores de la columna VARIABLES

        df_ph_copy['COLUMNA_VARIABLES'] = np.where(df_ph_copy['COLUMNA_VARIABLES'] == 'MAT_ORG' , 'MATERIA ORGANICA' , df_ph_copy['COLUMNA_VARIABLES'])
        df_ph_copy['COLUMNA_VARIABLES'] = np.where(df_ph_copy['COLUMNA_VARIABLES'] == 'DIV_SHANNON' , 'DISIDAD DE SHANNON' , df_ph_copy['COLUMNA_VARIABLES'])
        df_ph_copy['COLUMNA_VARIABLES'] = np.where(df_ph_copy['COLUMNA_VARIABLES'] == 'BIOM_TOTAL' , 'BIOMASA TOTAL' , df_ph_copy['COLUMNA_VARIABLES'])
        df_ph_copy['COLUMNA_VARIABLES'] = np.where(df_ph_copy['COLUMNA_VARIABLES'] == 'UNIF_PIELOU' , 'UNIFORMIDAD DE PIELOU' , df_ph_copy['COLUMNA_VARIABLES'])
        df_ph_copy['COLUMNA_VARIABLES'] = np.where(df_ph_copy['COLUMNA_VARIABLES'] == 'CLASIF_PERTURB' , 'CLASIFICACIÓN DE PERTURBACIÓN' , df_ph_copy['COLUMNA_VARIABLES'])
        df_ph_copy['COLUMNA_VARIABLES'] = np.where(df_ph_copy['COLUMNA_VARIABLES'] == 'N°_TAXA' , 'NUMERO DE TAXA' , df_ph_copy['COLUMNA_VARIABLES'])
        df_ph_copy['COLUMNA_VARIABLES'] = np.where(df_ph_copy['COLUMNA_VARIABLES'] == 'TEMP_REPL1' , 'TEMP_REPL_1' , df_ph_copy['COLUMNA_VARIABLES'])
        df_ph_copy['COLUMNA_VARIABLES'] = np.where(df_ph_copy['COLUMNA_VARIABLES'] == 'TEMP_REPL2' , 'TEMP_REPL_2' , df_ph_copy['COLUMNA_VARIABLES'])
        df_ph_copy['COLUMNA_VARIABLES'] = np.where(df_ph_copy['COLUMNA_VARIABLES'] == 'TEMP_REPL3' , 'TEMP_REPL_3' , df_ph_copy['COLUMNA_VARIABLES'])


        #Eliminamos las columnas innecesarias

        df_ph_copy = df_ph_copy[['ID', 'NOMB_PROY', 'COD_PROY', 'ETAP_PROY', 'JEFE_PROY', 'INST_PROY',
       'NOM_SECTOR', 'COD_REG', 'FECHA_INI', 'FECHA_TER','HORA_INI', 'N_ESTACION', 'LATITUD', 'LONGITUD', 'PROF_SECT',
       'COLUMNA_VARIABLES', 'VALOR', 'FECHA_INICIO']]

      
        df_ph_copy['ORIGEN'] = 'BD_COMPU_ph_Rx_T_2019'



        
        return df_ph_copy , columnas , columnas_fijas , columnas_variables

    except Exception as e:
        print(f"Ocurrió un error en la función limpieza_ctd: {e}")
        ex = sys.exc_info()[2]
        print("Error en el archivo : " + str(ex.tb_frame) + " En la linea : " + str(ex.tb_lineno))
            
        return None  # O devuelve un valor que indique el fallo

In [ ]:
df_ph_copy , columnas , columnas_fijas , columnas_variables = limpieza_ph(df_compu_ph)

In [ ]:
df_ph_copy['FECHA_INICIO'].unique()

array(['13/09/2019 19:07:00', '13/09/2019 19:26:00',
       '13/09/2019 19:36:00', '13/09/2019 18:09:00',
       '13/09/2019 18:29:00', '13/09/2019 18:51:00',
       '13/09/2019 17:50:00', '13/09/2019 16:52:00',
       '13/09/2019 16:57:00', '13/09/2019 16:40:00',
       '13/09/2019 21:55:00', '13/09/2019 21:50:00',
       '13/09/2019 21:30:00', '13/09/2019 14:45:00',
       '13/09/2019 18:57:00', '08/11/2019 00:00:00',
       '07/11/2019 00:00:00', '06/02/2020 09:54:00',
       '06/02/2020 10:08:00', '06/02/2020 10:39:00',
       '06/02/2020 10:54:00', '06/02/2020 11:20:00',
       '06/02/2020 11:35:00', '06/02/2020 12:16:00',
       '06/02/2020 12:43:00', '06/02/2020 13:02:00',
       '06/02/2020 13:40:00', '06/02/2020 15:24:00',
       '05/02/2020 19:14:00', '06/02/2020 15:40:00',
       '06/02/2020 16:15:00', '05/02/2020 19:38:00',
       '05/02/2020 17:31:00', '05/02/2020 18:37:00',
       '06/02/2020 09:33:00', '05/02/2020 10:45:00',
       '05/02/2020 14:31:00'], dtype=object)

In [ ]:
df_ph_copy['COLUMNA_VARIABLES'].unique()

array(['PROF_VAR', 'PH_REPL_1', 'PH_REPL_2', 'PH_REPL_3', 'TEMP_REPL_1',
       'TEMP_REPL_2', 'TEMP_REPL_3', 'REDOX_REPL_1', 'REDOX_REPL_2',
       'REDOX_REPL_3'], dtype=object)

# Limpieza de datos de PH_RX_T

In [ ]:
df_comau_ph = pd.read_excel(r'C:\Users\Felipe Abarzúa\Desktop\DATA_AMBIENTALES\Proyecto Seguimiento Ambiental\2019_P656115\5_BD_COMAU_ph_Rx_T_2019.xlsx' , sheet_name = 'Fiordo Comau dic_ene_feb')

In [ ]:
def limpieza_ph_comau(df):

    try:
        #Eliminamos las filas innecesarias
        df = df.iloc[14: , :-1]

        #Realizamos copia del dataset
        df_ph_copy = df.copy()

        #Reiniciamos los indices del dataset
        df_ph_copy = df_ph_copy.reset_index(drop=True)

        #Dejamos la primera fila como columna
        df_ph_copy.columns = df_ph_copy.iloc[0]

        #Eliminamos la primera fila 
        df_ph_copy = df_ph_copy.iloc[1: , :]

        #reiniciamos los indices
        df_ph_copy = df_ph_copy.reset_index(drop=True)

        #Creamos una columna de id 
        df_ph_copy.insert(0 , 'ID' , df_ph_copy.index + 1)

        #Renombramos las columnas del dataframe
        df_ph_copy = df_ph_copy.rename(columns={' COT_mg C' : 'COT_mg_C' , 'LONGUITUD' : 'LONGITUD' , 'COT_ug C' : 'COT_ug_C'})

        #Creamos una lista de columnas
        columnas = df_ph_copy.columns.to_list()

        #Creamos dos listas para despues unirlas para crear las columnas fijas
        columnas_fijas_1 = columnas[:16] 
        columnas_fijas_2 = columnas[-1:]

        columnas_fijas = columnas_fijas_1 + columnas_fijas_2
        columnas_variables = columnas[16:-1]

        
        """
              Realizamos un melt para convertir las columnas de Variables a filas

            Necesita:
            1. Dataframe a cambiar
            2. id_vars : Lista o Tupla de las columnas Fijas
            3. value_vars : Lista o Tupla de las columnas de Variables
            4. var_name : Nombre de la nueva columna de las Variables
            5. value_name : Nombre de la columna con los valores de la columna de Variables


        """

        df_ph_copy = pd.melt(df_ph_copy , id_vars= columnas_fijas , value_vars= columnas_variables , var_name = 'COLUMNA_VARIABLES' , value_name= 'VALOR' )

        #Cambiamos la columna HORA_INI
        df_ph_copy['HORA_INI'] = df_ph_copy['HORA_INI'].astype(str)

        #Reemplazamos los nan de la HORA_INI por 00:00:00
        df_ph_copy['HORA_INI'] = np.where(df_ph_copy['HORA_INI'] == 'nan' , '00:00:00' , df_ph_copy['HORA_INI'])

        #Creamos una columna de FECHA_INICIO
    
        df_ph_copy.insert(12 , 'FECHA_INICIO' , pd.to_datetime(df_ph_copy['FECHA_INI'].dt.strftime('%Y-%m-%d') + ' ' + df_ph_copy['HORA_INI']) )

        #Formateamos la columna FECHA_INICIO a DD/MM/YYYY HH:MI:SS
        df_ph_copy['FECHA_INICIO'] = pd.to_datetime(df_ph_copy['FECHA_INICIO'] ,  format='%d/%m/%Y %H:%M:%S')


        #Cambiamos el nombre de la columna 
        df_ph_copy['NOMB_PROY'] = 'ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICULTURA EN CHILE Y SU EFECTO EN LOS ECOSISTEMAS DE EMPLAZAMIENTO 2019-2020'


        #Dejamos la columna de variables en mayuscula 

        df_ph_copy['COLUMNA_VARIABLES'] = df_ph_copy['COLUMNA_VARIABLES'].str.upper()

        #Reemplazamos los valores de la columna VARIABLES

        df_ph_copy['COLUMNA_VARIABLES'] = np.where(df_ph_copy['COLUMNA_VARIABLES'] == 'MAT_ORG' , 'MATERIA ORGANICA' , df_ph_copy['COLUMNA_VARIABLES'])
        df_ph_copy['COLUMNA_VARIABLES'] = np.where(df_ph_copy['COLUMNA_VARIABLES'] == 'DIV_SHANNON' , 'DISIDAD DE SHANNON' , df_ph_copy['COLUMNA_VARIABLES'])
        df_ph_copy['COLUMNA_VARIABLES'] = np.where(df_ph_copy['COLUMNA_VARIABLES'] == 'BIOM_TOTAL' , 'BIOMASA TOTAL' , df_ph_copy['COLUMNA_VARIABLES'])
        df_ph_copy['COLUMNA_VARIABLES'] = np.where(df_ph_copy['COLUMNA_VARIABLES'] == 'UNIF_PIELOU' , 'UNIFORMIDAD DE PIELOU' , df_ph_copy['COLUMNA_VARIABLES'])
        df_ph_copy['COLUMNA_VARIABLES'] = np.where(df_ph_copy['COLUMNA_VARIABLES'] == 'CLASIF_PERTURB' , 'CLASIFICACIÓN DE PERTURBACIÓN' , df_ph_copy['COLUMNA_VARIABLES'])
        df_ph_copy['COLUMNA_VARIABLES'] = np.where(df_ph_copy['COLUMNA_VARIABLES'] == 'N°_TAXA' , 'NUMERO DE TAXA' , df_ph_copy['COLUMNA_VARIABLES'])
        
        
        #Eliminamos las columnas innecesarias

        df_ph_copy = df_ph_copy[['ID', 'NOMB_PROY', 'COD_PROY', 'ETAP_PROY', 'JEFE_PROY', 'INST_PROY',    'NOM_SECTOR', 'COD_REG', 'FECHA_INI', 'FECHA_TER',
       'HORA_INI', 'FECHA_INICIO', 'N_ESTACION', 'LATITUD', 'LONGITUD', 'PROF_SECT', 'COLUMNA_VARIABLES', 'VALOR']]



        df_ph_copy['FECHA_INICIO'] = df_ph_copy['FECHA_INICIO'].dt.strftime('%d/%m/%Y %H:%M:%S')

        df_ph_copy['ORIGEN'] = 'BD_COMAU_ph_Rx_T_2019'


        return df_ph_copy , columnas , columnas_fijas ,  columnas_variables

    
    except Exception as e:
        print(f"Ocurrió un error en la función limpieza_ph_comau: {e}")
        ex = sys.exc_info()[2]
        print("Error en el archivo : " + str(ex.tb_frame) + " En la linea : " + str(ex.tb_lineno))
            
        return None  # O devuelve un valor que indique el fallo

In [ ]:
df_comau_ph_copy , columnas , columnas_fijas , columnas_variables= limpieza_ph_comau(df_comau_ph)

In [ ]:
df_comau_ph_copy['FECHA_INICIO'].unique()

array(['18/12/2019 17:05:00', '18/12/2019 18:36:00', nan,
       '18/12/2019 16:09:00', '18/12/2019 14:49:00',
       '18/12/2019 10:00:00', '18/12/2019 10:35:00',
       '18/12/2019 12:13:00', '17/12/2019 09:40:00',
       '17/12/2019 11:23:00', '16/12/2019 18:30:00',
       '16/12/2019 17:33:00', '16/12/2019 17:09:00',
       '16/12/2019 11:57:00', '16/12/2019 11:33:00',
       '16/12/2019 09:10:00', '15/12/2019 16:38:00',
       '15/12/2019 18:05:00', '17/12/2019 13:47:00',
       '17/12/2019 14:20:00', '17/12/2019 16:15:00',
       '04/02/2020 09:10:00', '04/02/2020 09:37:00',
       '03/02/2020 16:58:00', '03/02/2020 17:32:00',
       '03/02/2020 14:31:00', '03/02/2020 15:05:00',
       '03/02/2020 15:54:00', '02/02/2020 13:47:00',
       '02/02/2020 14:43:00', '02/02/2020 10:04:00',
       '02/02/2020 09:24:00', '02/02/2020 08:29:00',
       '01/02/2020 12:47:00', '01/02/2020 08:20:00',
       '31/01/2020 19:09:00', '31/01/2020 15:47:00',
       '31/01/2020 17:51:00', '02/02/2020 15:14:00',
       '02/02/2020 16:44:00', '02/02/2020 18:50:00',
       '26/02/2020 08:59:00', '26/02/2020 09:47:00',
       '25/02/2020 09:53:00', '25/02/2020 11:59:00',
       '21/02/2020 09:31:00', '21/02/2020 12:12:00',
       '22/02/2020 18:00:00', '20/02/2020 18:24:00',
       '20/02/2020 11:20:00', '20/02/2020 10:12:00',
       '20/02/2020 08:48:00', '20/02/2020 14:53:00',
       '19/02/2020 16:52:00', '19/02/2020 14:39:00',
       '19/02/2020 08:11:00', '19/02/2020 11:03:00',
       '22/02/2020 14:58:00', '22/02/2020 11:06:00',
       '22/02/2020 09:58:00'], dtype=object)

# Limpieza BD Muestreo Regular Seguimiento 2019

In [ ]:
df_muestreo_regular = pd.read_excel(r'C:\Users\Felipe Abarzúa\Desktop\DATA_AMBIENTALES\Proyecto Seguimiento Ambiental\2019_P656115\1_BD_MuestreoRegular_SEGUIMIENTO_2019.xlsx' , sheet_name='BD_Seguimiento_Ambiental_IFOP19')

In [ ]:
df_muestreo_regular

,Nombre del Proyecto:,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICULTURA EN CHILE Y SU EFECTO EN LOS ECOSISTEMAS DE EMPLAZAMIENTO 2019 -2020,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38
0,Codigo del Proyecto:,656-115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Etapa Proyecto:,Objetivo 1. Actividad 2. Muestreos y Analisis ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Jefe Proyecto,Gastón Vidal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Institucion:,INSTITUTO DE FOMENTO PESQUERO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Nombre Sector:,"Atacama (Caldera-Bahia Inglesa), Coquimbo (Ton...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,Objetivo 1. Actividad 2. Muestreos y Analisis ...,GASTON VIDAL,INSTITUTO DE FOMENTO PESQUERO,Natales,XII,"Ph, Temperatura (°C), Redox EHNHE (mV), Sulfur...",2019-08-11 00:00:00,2019-08-11 00:00:00,...,1520,13,10.042,0.7994,0.7176,1.283,Ligeramente perturbado,NaN,NaN,45
182,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,Objetivo 1. Actividad 2. Muestreos y Analisis ...,GASTON VIDAL,INSTITUTO DE FOMENTO PESQUERO,Natales,XII,"Ph, Temperatura (°C), Redox EHNHE (mV), Sulfur...",2019-08-11 00:00:00,2019-08-11 00:00:00,...,230,11,1.088,0.9806,0.9416,1.705,Ligeramente perturbado,NaN,NaN,48
183,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,Objetivo 1. Actividad 2. Muestreos y Analisis ...,GASTON VIDAL,INSTITUTO DE FOMENTO PESQUERO,Natales,XII,"Ph, Temperatura (°C), Redox EHNHE (mV), Sulfur...",2019-08-11 00:00:00,2019-08-11 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No corresponde muestra de macrofauna,48
184,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,Objetivo 1. Actividad 2. Muestreos y Analisis ...,GASTON VIDAL,INSTITUTO DE FOMENTO PESQUERO,Natales,XII,"Ph, Temperatura (°C), Redox EHNHE (mV), Sulfur...",2019-08-11 00:00:00,2019-08-11 00:00:00,...,5410,17,4.606,0.4952,0.4025,1.912,Ligeramente perturbado,NaN,NaN,47a
185,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,Objetivo 1. Actividad 2. Muestreos y Analisis ...,GASTON VIDAL,INSTITUTO DE FOMENTO PESQUERO,Natales,XII,"Ph, Temperatura (°C), Redox EHNHE (mV), Sulfur...",2019-08-11 00:00:00,2019-08-11 00:00:00,...,1610,14,0.996,0.8131,0.7094,1.488,Ligeramente perturbado,NaN,NaN,46

In [ ]:
def limpieza_muestreo_regular(df):

    try:
        
        #Eliminamos filas innecesarias
        df = df.iloc[15: , :]

        #Creamos una copia del dataset 
        df_muestreo_regular_copy = df.copy()

        #Reiniciamos los indices del dataframe
        df_muestreo_regular_copy = df_muestreo_regular_copy.reset_index(drop = True)

        #Dejamos la primera fila como columnas 
        df_muestreo_regular_copy.columns = df_muestreo_regular_copy.iloc[0]

        #Eliminamos la primera fila del dataframe 
        df_muestreo_regular_copy = df_muestreo_regular_copy.iloc[1: , :]

        #Volvemos a reiniciar los indices del dataframe
        df_muestreo_regular_copy = df_muestreo_regular_copy.reset_index(drop = True)

        #Renombramos las columnas 
        df_muestreo_regular_copy =  df_muestreo_regular_copy.rename(columns = {'LONGUITUD' : 'LONGITUD'})

        #Agregamos una columna de ID 
        df_muestreo_regular_copy.insert(0, 'ID' , df_muestreo_regular_copy.index + 1)

        #Creamos una lista de las columnas 
        columnas = df_muestreo_regular_copy.columns.to_list()

        #Creamos la lista de columnas fijas y variables
        columnas_fijas_1 = columnas[:16]
        columnas_fijas_2 = columnas[-3:]

        columnas_fijas = columnas_fijas_1 + columnas_fijas_2
        columnas_variables = columnas[16:]

              
        """
              Realizamos un melt para convertir las columnas de Variables a filas

            Necesita:
            1. Dataframe a cambiar
            2. id_vars : Lista o Tupla de las columnas Fijas
            3. value_vars : Lista o Tupla de las columnas de Variables
            4. var_name : Nombre de la nueva columna de las Variables
            5. value_name : Nombre de la columna con los valores de la columna de Variables


        """

        df_muestreo_regular_copy = pd.melt(df_muestreo_regular_copy , id_vars= columnas_fijas , value_vars=columnas_variables , var_name= 'COLUMNA_VARIABLES' , value_name='VALOR')

        #Cambiamos el tipo de dato de HORA_INI a string 

        df_muestreo_regular_copy['HORA_INI'] =  df_muestreo_regular_copy['HORA_INI'].astype(str)
        
        #Realizamos un replace para cambiar las HORA_INI
        df_muestreo_regular_copy['HORA_INI'] = np.where(df_muestreo_regular_copy['HORA_INI'] == '1927-05-17 23:45:36' , '23:45:36' , df_muestreo_regular_copy['HORA_INI'])
        df_muestreo_regular_copy['HORA_INI'] = np.where(df_muestreo_regular_copy['HORA_INI'] == 'nan' , '00:00:00' , df_muestreo_regular_copy['HORA_INI'])
        
        #Luego creamos una columna llamada FECHA_INICIO 
        df_muestreo_regular_copy.insert(12 , 'FECHA_INICIO' , pd.to_datetime(df_muestreo_regular_copy['FECHA_INI'].dt.strftime('%Y-%m-%d') + ' ' + df_muestreo_regular_copy['HORA_INI'])) 

        #Formateamos la columna FECHA_INICIO a DD/MM/YYYY HH:MI:SS
        df_muestreo_regular_copy['FECHA_INICIO'] = pd.to_datetime(df_muestreo_regular_copy['FECHA_INICIO'] ,  format='%d/%m/%Y %H:%M:%S')

        #Convertimos la columna de VARIABLES a mayuscula

        df_muestreo_regular_copy['COLUMNA_VARIABLES'] = df_muestreo_regular_copy['COLUMNA_VARIABLES'].str.upper()

        #Reemplazamos los valores de la columna VARIABLES

        df_muestreo_regular_copy['COLUMNA_VARIABLES'] = np.where(df_muestreo_regular_copy['COLUMNA_VARIABLES'] == 'MAT_ORG' , 'MATERIA ORGANICA' , df_muestreo_regular_copy['COLUMNA_VARIABLES'])
        df_muestreo_regular_copy['COLUMNA_VARIABLES'] = np.where(df_muestreo_regular_copy['COLUMNA_VARIABLES'] == 'DIV_SHANNON' , 'DISIDAD DE SHANNON' , df_muestreo_regular_copy['COLUMNA_VARIABLES'])
        df_muestreo_regular_copy['COLUMNA_VARIABLES'] = np.where(df_muestreo_regular_copy['COLUMNA_VARIABLES'] == 'BIOM_TOTAL' , 'BIOMASA TOTAL' , df_muestreo_regular_copy['COLUMNA_VARIABLES'])
        df_muestreo_regular_copy['COLUMNA_VARIABLES'] = np.where(df_muestreo_regular_copy['COLUMNA_VARIABLES'] == 'UNIF_PIELOU' , 'UNIFORMIDAD DE PIELOU' , df_muestreo_regular_copy['COLUMNA_VARIABLES'])
        df_muestreo_regular_copy['COLUMNA_VARIABLES'] = np.where(df_muestreo_regular_copy['COLUMNA_VARIABLES'] == 'CLASIF_PERTURB' , 'CLASIFICACIÓN DE PERTURBACIÓN' , df_muestreo_regular_copy['COLUMNA_VARIABLES'])
        df_muestreo_regular_copy['COLUMNA_VARIABLES'] = np.where(df_muestreo_regular_copy['COLUMNA_VARIABLES'] == 'N°_TAXA' , 'NUMERO DE TAXA' , df_muestreo_regular_copy['COLUMNA_VARIABLES'])
        df_muestreo_regular_copy['COLUMNA_VARIABLES'] = np.where(df_muestreo_regular_copy['COLUMNA_VARIABLES'] == 'ABUNDANCIA' , 'ABUNDANCIA TOTAL' , df_muestreo_regular_copy['COLUMNA_VARIABLES'])

      
        # Eliminamos las columnas innecesarias del archivo

        df_muestreo_regular_copy = df_muestreo_regular_copy[['ID', 'NOMB_PROY', 'COD_PROY', 'ETAP_PROY', 'JEFE_PROY', 'INST_PROY',
       'NOM_SECTOR', 'COD_REG', 'VARIABLE', 'FECHA_INI', 'FECHA_TER','HORA_INI', 'FECHA_INICIO', 'N_ESTACION', 'LATITUD', 'LONGITUD',  'PROF_SECT', 'COLUMNA_VARIABLES', 'VALOR']]
        
        

        df_muestreo_regular_copy['FECHA_INICIO'] = df_muestreo_regular_copy['FECHA_INICIO'].dt.strftime('%d/%m/%Y %H:%M:%S')


        df_muestreo_regular_copy['ORIGEN'] = 'BD_MuestreoRegular_SEGUIMIENTO_2019'



        return df_muestreo_regular_copy , columnas_fijas , columnas_variables


    except Exception as e:
        print(f"Ocurrió un error en la función limpieza_muestreo_regular: {e}")
        ex = sys.exc_info()[2]
        print("Error en el archivo : " + str(ex.tb_frame) + " En la linea : " + str(ex.tb_lineno))

In [ ]:
df_muestreo_regular_copy , columnas_fijas , columnas_variables = limpieza_muestreo_regular(df_muestreo_regular)

In [ ]:
df_muestreo_regular_copy['FECHA_INICIO'].unique()

array(['11/04/2019 00:00:00', '11/04/2019 23:45:36',
       '15/04/2019 00:00:00', '24/07/2019 23:45:36',
       '26/07/2019 00:00:00', '10/05/2019 15:55:00',
       '10/05/2019 16:40:00', '10/05/2019 14:55:00',
       '10/05/2019 12:55:00', '10/05/2019 11:18:00',
       '10/05/2019 12:20:00', '10/05/2019 10:25:00',
       '10/05/2019 09:55:00', '10/05/2019 09:02:00',
       '10/05/2019 08:15:00', '12/05/2019 15:40:00',
       '12/05/2019 00:00:00', '30/05/2019 11:00:00',
       '09/05/2019 00:00:00', '12/05/2019 14:30:00',
       '30/05/2019 00:00:00', '30/05/2019 13:15:00',
       '02/06/2019 00:00:00', '30/05/2019 15:00:00',
       '30/05/2019 16:20:00', '02/06/2019 16:46:00',
       '02/06/2019 16:00:00', '02/06/2019 15:18:00',
       '06/06/2019 23:45:36', '03/06/2019 23:45:36',
       '03/06/2019 09:20:00', '03/06/2019 08:35:00',
       '08/06/2019 08:11:00', '08/06/2019 08:45:00',
       '06/06/2019 00:00:00', '06/06/2019 17:26:00',
       '06/06/2019 17:00:00', '07/06/2019 13:42:00',
       '07/06/2019 12:22:00', '07/06/2019 00:00:00',
       '07/06/2019 11:00:00', '07/06/2019 16:00:00',
       '07/06/2019 17:56:00', '15/05/2019 00:00:00',
       '09/06/2019 16:56:00', '09/06/2019 17:49:00',
       '09/06/2019 18:24:00', '09/06/2019 16:02:00',
       '09/06/2019 15:10:00', '09/06/2019 13:09:00',
       '09/06/2019 12:40:00', '09/06/2019 11:59:00',
       '09/06/2019 11:00:00', '09/06/2019 09:09:00',
       '09/06/2019 10:10:00', '08/06/2019 14:10:00',
       '13/05/2019 00:00:00', '14/05/2019 00:00:00',
       '16/05/2019 00:00:00', '20/05/2019 00:00:00',
       '19/05/2019 00:00:00', '18/05/2019 00:00:00',
       '14/06/2019 15:12:00', '14/06/2019 13:40:00',
       '14/06/2019 11:34:00', '14/06/2019 10:10:00',
       '14/06/2019 08:50:00', '13/06/2019 09:54:00',
       '13/06/2019 08:55:00', '13/06/2019 10:53:00',
       '13/06/2019 00:00:00', '13/06/2019 15:50:00',
       '15/06/2019 17:17:00', '15/06/2019 16:20:00',
       '15/06/2019 14:55:00', '15/06/2019 09:55:00',
       '15/06/2019 09:00:00', '14/06/2019 17:22:00',
       '14/06/2019 16:20:00', '13/06/2019 14:00:00',
       '25/06/2019 16:02:00', '24/06/2019 10:30:00',
       '25/06/2019 11:45:00', '25/06/2019 09:06:00',
       '25/06/2019 08:25:00', '24/06/2019 15:17:00',
       '24/06/2019 14:05:00', '18/06/2019 10:38:00',
       '18/06/2019 13:15:00', '17/06/2019 15:52:00',
       '17/06/2019 11:55:00', '17/06/2019 08:55:00',
       '19/06/2019 14:50:00', '19/06/2019 15:39:00',
       '20/06/2019 08:44:00', '21/06/2019 14:01:00',
       '21/06/2019 15:00:00', '16/06/2019 15:20:00',
       '16/06/2019 13:30:00', '16/06/2019 11:55:00',
       '16/06/2019 10:20:00', '23/06/2019 11:00:00',
       '10/08/2019 15:24:00', '10/08/2019 16:19:00',
       '11/08/2019 22:45:00', '11/08/2019 12:49:00',
       '11/08/2019 15:43:00', '11/08/2019 17:58:00',
       '11/08/2019 18:40:00', '11/08/2019 10:16:00'], dtype=object)

In [ ]:
df_comau_ph_copy['FECHA_INICIO'].unique()

array(['18/12/2019 17:05:00', '18/12/2019 18:36:00', nan,
       '18/12/2019 16:09:00', '18/12/2019 14:49:00',
       '18/12/2019 10:00:00', '18/12/2019 10:35:00',
       '18/12/2019 12:13:00', '17/12/2019 09:40:00',
       '17/12/2019 11:23:00', '16/12/2019 18:30:00',
       '16/12/2019 17:33:00', '16/12/2019 17:09:00',
       '16/12/2019 11:57:00', '16/12/2019 11:33:00',
       '16/12/2019 09:10:00', '15/12/2019 16:38:00',
       '15/12/2019 18:05:00', '17/12/2019 13:47:00',
       '17/12/2019 14:20:00', '17/12/2019 16:15:00',
       '04/02/2020 09:10:00', '04/02/2020 09:37:00',
       '03/02/2020 16:58:00', '03/02/2020 17:32:00',
       '03/02/2020 14:31:00', '03/02/2020 15:05:00',
       '03/02/2020 15:54:00', '02/02/2020 13:47:00',
       '02/02/2020 14:43:00', '02/02/2020 10:04:00',
       '02/02/2020 09:24:00', '02/02/2020 08:29:00',
       '01/02/2020 12:47:00', '01/02/2020 08:20:00',
       '31/01/2020 19:09:00', '31/01/2020 15:47:00',
       '31/01/2020 17:51:00', '02/02/2020 15:14:00',
       '02/02/2020 16:44:00', '02/02/2020 18:50:00',
       '26/02/2020 08:59:00', '26/02/2020 09:47:00',
       '25/02/2020 09:53:00', '25/02/2020 11:59:00',
       '21/02/2020 09:31:00', '21/02/2020 12:12:00',
       '22/02/2020 18:00:00', '20/02/2020 18:24:00',
       '20/02/2020 11:20:00', '20/02/2020 10:12:00',
       '20/02/2020 08:48:00', '20/02/2020 14:53:00',
       '19/02/2020 16:52:00', '19/02/2020 14:39:00',
       '19/02/2020 08:11:00', '19/02/2020 11:03:00',
       '22/02/2020 14:58:00', '22/02/2020 11:06:00',
       '22/02/2020 09:58:00'], dtype=object)

In [ ]:
df_ph_copy['FECHA_INICIO'].unique()

array(['13/09/2019 19:07:00', '13/09/2019 19:26:00',
       '13/09/2019 19:36:00', '13/09/2019 18:09:00',
       '13/09/2019 18:29:00', '13/09/2019 18:51:00',
       '13/09/2019 17:50:00', '13/09/2019 16:52:00',
       '13/09/2019 16:57:00', '13/09/2019 16:40:00',
       '13/09/2019 21:55:00', '13/09/2019 21:50:00',
       '13/09/2019 21:30:00', '13/09/2019 14:45:00',
       '13/09/2019 18:57:00', '08/11/2019 00:00:00',
       '07/11/2019 00:00:00', '06/02/2020 09:54:00',
       '06/02/2020 10:08:00', '06/02/2020 10:39:00',
       '06/02/2020 10:54:00', '06/02/2020 11:20:00',
       '06/02/2020 11:35:00', '06/02/2020 12:16:00',
       '06/02/2020 12:43:00', '06/02/2020 13:02:00',
       '06/02/2020 13:40:00', '06/02/2020 15:24:00',
       '05/02/2020 19:14:00', '06/02/2020 15:40:00',
       '06/02/2020 16:15:00', '05/02/2020 19:38:00',
       '05/02/2020 17:31:00', '05/02/2020 18:37:00',
       '06/02/2020 09:33:00', '05/02/2020 10:45:00',
       '05/02/2020 14:31:00'], dtype=object)

In [ ]:
df_ph_copy.columns

Index(['ID', 'NOMB_PROY', 'COD_PROY', 'ETAP_PROY', 'JEFE_PROY', 'INST_PROY',
       'NOM_SECTOR', 'COD_REG', 'FECHA_INI', 'FECHA_TER', 'HORA_INI',
       'N_ESTACION', 'LATITUD', 'LONGITUD', 'PROF_SECT', 'COLUMNA_VARIABLES',
       'VALOR', 'FECHA_INICIO', 'ORIGEN'],
      dtype='object')

In [ ]:
# Realizamos la union entre los 3 dataframes 

df_muestreo_regular_merge = pd.concat([df_muestreo_regular_copy , df_comau_ph_copy ,df_ph_copy ] , ignore_index= True)

# Modificamos la columna NOMB_PROY 

df_muestreo_regular_merge['NOMB_PROY'] = 'ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICULTURA EN CHILE Y SU EFECTO EN LOS ECOSISTEMAS DE EMPLAZAMIENTO 2019-2020'

# Cambiamos el COD_PROY

df_muestreo_regular_merge['COD_PROY'] = '656-115'


# Cambiamos los 'FIORDO COMAU', 'FIORDO COMPU'

df_muestreo_regular_merge['NOM_SECTOR'] = np.where(df_muestreo_regular_merge['NOM_SECTOR'] == 'FIORDO COMAU' , 'Fiordo Comau', df_muestreo_regular_merge['NOM_SECTOR'])
df_muestreo_regular_merge['NOM_SECTOR'] = np.where(df_muestreo_regular_merge['NOM_SECTOR'] == 'FIORDO COMPU' , 'Fiordo Compu', df_muestreo_regular_merge['NOM_SECTOR'])

In [ ]:
df_muestreo_regular_merge['FECHA_INICIO'].unique()

array(['11/04/2019 00:00:00', '11/04/2019 23:45:36',
       '15/04/2019 00:00:00', '24/07/2019 23:45:36',
       '26/07/2019 00:00:00', '10/05/2019 15:55:00',
       '10/05/2019 16:40:00', '10/05/2019 14:55:00',
       '10/05/2019 12:55:00', '10/05/2019 11:18:00',
       '10/05/2019 12:20:00', '10/05/2019 10:25:00',
       '10/05/2019 09:55:00', '10/05/2019 09:02:00',
       '10/05/2019 08:15:00', '12/05/2019 15:40:00',
       '12/05/2019 00:00:00', '30/05/2019 11:00:00',
       '09/05/2019 00:00:00', '12/05/2019 14:30:00',
       '30/05/2019 00:00:00', '30/05/2019 13:15:00',
       '02/06/2019 00:00:00', '30/05/2019 15:00:00',
       '30/05/2019 16:20:00', '02/06/2019 16:46:00',
       '02/06/2019 16:00:00', '02/06/2019 15:18:00',
       '06/06/2019 23:45:36', '03/06/2019 23:45:36',
       '03/06/2019 09:20:00', '03/06/2019 08:35:00',
       '08/06/2019 08:11:00', '08/06/2019 08:45:00',
       '06/06/2019 00:00:00', '06/06/2019 17:26:00',
       '06/06/2019 17:00:00', '07/06/2019 13:42:00',
       '07/06/2019 12:22:00', '07/06/2019 00:00:00',
       '07/06/2019 11:00:00', '07/06/2019 16:00:00',
       '07/06/2019 17:56:00', '15/05/2019 00:00:00',
       '09/06/2019 16:56:00', '09/06/2019 17:49:00',
       '09/06/2019 18:24:00', '09/06/2019 16:02:00',
       '09/06/2019 15:10:00', '09/06/2019 13:09:00',
       '09/06/2019 12:40:00', '09/06/2019 11:59:00',
       '09/06/2019 11:00:00', '09/06/2019 09:09:00',
       '09/06/2019 10:10:00', '08/06/2019 14:10:00',
       '13/05/2019 00:00:00', '14/05/2019 00:00:00',
       '16/05/2019 00:00:00', '20/05/2019 00:00:00',
       '19/05/2019 00:00:00', '18/05/2019 00:00:00',
       '14/06/2019 15:12:00', '14/06/2019 13:40:00',
       '14/06/2019 11:34:00', '14/06/2019 10:10:00',
       '14/06/2019 08:50:00', '13/06/2019 09:54:00',
       '13/06/2019 08:55:00', '13/06/2019 10:53:00',
       '13/06/2019 00:00:00', '13/06/2019 15:50:00',
       '15/06/2019 17:17:00', '15/06/2019 16:20:00',
       '15/06/2019 14:55:00', '15/06/2019 09:55:00',
       '15/06/2019 09:00:00', '14/06/2019 17:22:00',
       '14/06/2019 16:20:00', '13/06/2019 14:00:00',
       '25/06/2019 16:02:00', '24/06/2019 10:30:00',
       '25/06/2019 11:45:00', '25/06/2019 09:06:00',
       '25/06/2019 08:25:00', '24/06/2019 15:17:00',
       '24/06/2019 14:05:00', '18/06/2019 10:38:00',
       '18/06/2019 13:15:00', '17/06/2019 15:52:00',
       '17/06/2019 11:55:00', '17/06/2019 08:55:00',
       '19/06/2019 14:50:00', '19/06/2019 15:39:00',
       '20/06/2019 08:44:00', '21/06/2019 14:01:00',
       '21/06/2019 15:00:00', '16/06/2019 15:20:00',
       '16/06/2019 13:30:00', '16/06/2019 11:55:00',
       '16/06/2019 10:20:00', '23/06/2019 11:00:00',
       '10/08/2019 15:24:00', '10/08/2019 16:19:00',
       '11/08/2019 22:45:00', '11/08/2019 12:49:00',
       '11/08/2019 15:43:00', '11/08/2019 17:58:00',
       '11/08/2019 18:40:00', '11/08/2019 10:16:00',
       '18/12/2019 17:05:00', '18/12/2019 18:36:00', nan,
       '18/12/2019 16:09:00', '18/12/2019 14:49:00',
       '18/12/2019 10:00:00', '18/12/2019 10:35:00',
       '18/12/2019 12:13:00', '17/12/2019 09:40:00',
       '17/12/2019 11:23:00', '16/12/2019 18:30:00',
       '16/12/2019 17:33:00', '16/12/2019 17:09:00',
       '16/12/2019 11:57:00', '16/12/2019 11:33:00',
       '16/12/2019 09:10:00', '15/12/2019 16:38:00',
       '15/12/2019 18:05:00', '17/12/2019 13:47:00',
       '17/12/2019 14:20:00', '17/12/2019 16:15:00',
       '04/02/2020 09:10:00', '04/02/2020 09:37:00',
       '03/02/2020 16:58:00', '03/02/2020 17:32:00',
       '03/02/2020 14:31:00', '03/02/2020 15:05:00',
       '03/02/2020 15:54:00', '02/02/2020 13:47:00',
       '02/02/2020 14:43:00', '02/02/2020 10:04:00',
       '02/02/2020 09:24:00', '02/02/2020 08:29:00',
       '01/02/2020 12:47:00', '01/02/2020 08:20:00',
       '31/01/2020 19:09:00', '31/01/2020 15:47:00',
       '31/01/2020 17:51:00', '02/02/2020 15:14:00',
       '02/02/2020 16:44:00', '02/02/2020 18:50:00',
       '26/02/2020 08:59:00', '26/02/2020 09:47:00',
       '25/02/2020 09:53:00', '25/02/2020 11:59:00',
       '21/02/2020 09:31:00', '21/02/2020 12:12:00',
       '22/02/2020 18:00:00', '20/02/2020 18:24:00',
       '20/02/2020 11:20:00', '20/02/2020 10:12:00',
       '20/02/2020 08:48:00', '20/02/2020 14:53:00',
       '19/02/2020 16:52:00', '19/02/2020 14:39:00',
       '19/02/2020 08:11:00', '19/02/2020 11:03:00',
       '22/02/2020 14:58:00', '22/02/2020 11:06:00',
       '22/02/2020 09:58:00', '13/09/2019 19:07:00',
       '13/09/2019 19:26:00', '13/09/2019 19:36:00',
       '13/09/2019 18:09:00', '13/09/2019 18:29:00',
       '13/09/2019 18:51:00', '13/09/2019 17:50:00',
       '13/09/2019 16:52:00', '13/09/2019 16:57:00',
       '13/09/2019 16:40:00', '13/09/2019 21:55:00',
       '13/09/2019 21:50:00', '13/09/2019 21:30:00',
       '13/09/2019 14:45:00', '13/09/2019 18:57:00',
       '08/11/2019 00:00:00', '07/11/2019 00:00:00',
       '06/02/2020 09:54:00', '06/02/2020 10:08:00',
       '06/02/2020 10:39:00', '06/02/2020 10:54:00',
       '06/02/2020 11:20:00', '06/02/2020 11:35:00',
       '06/02/2020 12:16:00', '06/02/2020 12:43:00',
       '06/02/2020 13:02:00', '06/02/2020 13:40:00',
       '06/02/2020 15:24:00', '05/02/2020 19:14:00',
       '06/02/2020 15:40:00', '06/02/2020 16:15:00',
       '05/02/2020 19:38:00', '05/02/2020 17:31:00',
       '05/02/2020 18:37:00', '06/02/2020 09:33:00',
       '05/02/2020 10:45:00', '05/02/2020 14:31:00'], dtype=object)

In [ ]:
df_muestreo_regular_merge.columns

Index(['ID', 'NOMB_PROY', 'COD_PROY', 'ETAP_PROY', 'JEFE_PROY', 'INST_PROY',
       'NOM_SECTOR', 'COD_REG', 'VARIABLE', 'FECHA_INI', 'FECHA_TER',
       'HORA_INI', 'FECHA_INICIO', 'N_ESTACION', 'LATITUD', 'LONGITUD',
       'PROF_SECT', 'COLUMNA_VARIABLES', 'VALOR', 'ORIGEN'],
      dtype='object')

In [ ]:
df_muestreo_regular_merge['FECHA_INI'].unique()

array([Timestamp('2019-04-11 00:00:00'), Timestamp('2019-04-15 00:00:00'),
       Timestamp('2019-07-24 00:00:00'), Timestamp('2019-07-26 00:00:00'),
       Timestamp('2019-05-10 00:00:00'), Timestamp('2019-05-12 00:00:00'),
       Timestamp('2019-05-30 00:00:00'), Timestamp('2019-05-09 00:00:00'),
       Timestamp('2019-06-02 00:00:00'), Timestamp('2019-06-06 00:00:00'),
       Timestamp('2019-06-03 00:00:00'), Timestamp('2019-06-08 00:00:00'),
       Timestamp('2019-06-07 00:00:00'), Timestamp('2019-05-15 00:00:00'),
       Timestamp('2019-06-09 00:00:00'), Timestamp('2019-05-13 00:00:00'),
       Timestamp('2019-05-14 00:00:00'), Timestamp('2019-05-16 00:00:00'),
       Timestamp('2019-05-20 00:00:00'), Timestamp('2019-05-19 00:00:00'),
       Timestamp('2019-05-18 00:00:00'), Timestamp('2019-06-14 00:00:00'),
       Timestamp('2019-06-13 00:00:00'), Timestamp('2019-06-15 00:00:00'),
       Timestamp('2019-06-25 00:00:00'), Timestamp('2019-06-24 00:00:00'),
       Timestamp('2019-06-18 00:00:00'), Timestamp('2019-06-17 00:00:00'),
       Timestamp('2019-06-19 00:00:00'), Timestamp('2019-06-20 00:00:00'),
       Timestamp('2019-06-21 00:00:00'), Timestamp('2019-06-16 00:00:00'),
       Timestamp('2019-06-23 00:00:00'), Timestamp('2019-08-10 00:00:00'),
       Timestamp('2019-08-11 00:00:00'), Timestamp('2019-12-18 00:00:00'),
       NaT, Timestamp('2019-12-17 00:00:00'),
       Timestamp('2019-12-16 00:00:00'), Timestamp('2019-12-15 00:00:00'),
       Timestamp('2020-02-04 00:00:00'), Timestamp('2020-02-03 00:00:00'),
       Timestamp('2020-02-02 00:00:00'), Timestamp('2020-02-01 00:00:00'),
       Timestamp('2020-01-31 00:00:00'), Timestamp('2020-02-26 00:00:00'),
       Timestamp('2020-02-25 00:00:00'), Timestamp('2020-02-21 00:00:00'),
       Timestamp('2020-02-22 00:00:00'), Timestamp('2020-02-20 00:00:00'),
       Timestamp('2020-02-19 00:00:00'), '2019-09-13', '2019-11-08',
       '2019-11-07', '2020-02-06', '2020-02-05'], dtype=object)

In [ ]:
df_muestreo_regular_merge['NOM_SECTOR'].unique()

array(['Atacama', 'Coquimbo', 'Bio-Bio', 'Valdivia', 'Estuario',
       'Reloncavi', 'Calbuco', 'Chacao', 'Butachauques', 'Chaulinec',
       'Tenaun', 'Chiloe central', 'Desertores', 'Quellon', 'Hornopiren',
       'Ayacara', 'Chaiten', 'Guaitecas', 'Moraleda', 'Puyuhuapi',
       'Aysen', 'Natales', 'Fiordo Comau', 'Fiordo Compu'], dtype=object)

In [ ]:
df_muestreo_regular_merge.to_excel('output/2019/AMBIENTALES_MUESTREO_REGULAR_TEST.xlsx' , index=False)

In [ ]:
df_muestreo_regular_merge.to_csv('output/2019/AMBIENTALES_MUESTREO_REGULAR_2019.csv' , index=False)

# Limpieza BD fisicos y quimicos Maullín

Este archivo contiene varias hojas , hay que almacenar todo dentro de un solo archivo o hay que separarlo.

In [4]:
df_fq = pd.read_excel(r'C:\Users\felipe.abarzua\Desktop\workspace\DATA_AMBIENTALES\Proyecto Seguimiento Ambiental\FISICO QUIMICOS_2012-2024\1_BD_FISICOQUIMICO_2019.xlsx')

In [5]:
df_fq

,Nombre del Proyecto:,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICULTURA EN CHILE Y SU EFECTO EN LOS ECOSISTEMAS DE EMPLAZAMIENTO 2019-2020,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,Etapa Proyecto:,Objetivo 1. Actividad 2. Muestreos y Analisis ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Jefe Proyecto,Gastón Vidal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Institucion:,INSTITUTO DE FOMENTO PESQUERO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Nombre Sector:,"Atacama (Caldera-Bahia Inglesa), Coquimbo (Ton...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Región:,"Región de Atacama, Región de Coquimbo, Región ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180,ESTUDIO DEL DESEMPEÑO AMBIENTAL DE LA ACUICULT...,Objetivo 1. Actividad 2. Muestreos y Analisis ...,Gastón Vidal,INSTITUTO DE FOMENTO PESQUERO,Campaña_Inv_Ver_2019.Proy.SeguimientoAmbiental,Valdivia,4,"39°51'53,8''","73°21'38,8''",7.176667,...,407.666667,33.838046,0.0,0.0,0.977428,1.5,s/i,2019-07-26 00:00:00,s/i,4
181,ESTUDIO DEL DESEMPEÑO AMBIENTAL DE LA ACUICULT...,Objetivo 1. Actividad 2. Muestreos y Analisis ...,Gastón Vidal,INSTITUTO DE FOMENTO PESQUERO,Campaña_Inv_Ver_2019.Proy.SeguimientoAmbiental,Valdivia,6,"39°52'46,5''","73°22'53,5''",7.543333,...,376.6,13.291727,0.0,0.0,1.309219,2.5,s/i,2019-07-26 00:00:00,s/i,6
182,ESTUDIO DEL DESEMPEÑO AMBIENTAL DE LA ACUICULT...,Objetivo 1. Actividad 2. Muestreos y Analisis ...,Gastón Vidal,INSTITUTO DE FOMENTO PESQUERO,Campaña_Inv_Ver_2019.Proy.SeguimientoAmbiental,Valdivia,9,"39°53'36,9''","73°21'46,5''",7.55,...,97.833333,20.886918,75.684237,48.737273,11.553874,2.5,s/i,2019-07-26 00:00:00,s/i,9
183,ESTUDIO DEL DESEMPEÑO AMBIENTAL DE LA ACUICULT...,Objetivo 1. Actividad 2. Muestreos y Analisis ...,Gastón Vidal,INSTITUTO DE FOMENTO PESQUERO,Campaña_Inv_Ver_2019.Proy.SeguimientoAmbiental,Valdivia,11,"39°53'35,9''","73°22'19,4''",7.48,...,180.6,16.89349,76.939347,53.757601,11.061239,1.5,s/i,2019-07-26 00:00:00,s/i,11
184,ESTUDIO DEL DESEMPEÑO AMBIENTAL DE LA ACUICULT...,Objetivo 1. Actividad 2. Muestreos y Analisis ...,Gastón Vidal,INSTITUTO DE FOMENTO PESQUERO,Campaña_Inv_Ver_2019.Proy.SeguimientoAmbiental,Valdivia,15,"39°55'47,5''","73°23'41,2''",7.616667,...,125.6,35.096296,8.533643,2.848958,10.240249,1.5,s/i,2019-07-26 00:00:00,s/i,15

In [20]:
df_termistor_final.columns

Index(['ID', 'NOMB_PROY', 'COD_PROY', 'FECHA_INI', 'FECHA_TER', 'EQUIPO',
       'LATITUD', 'LONGITUD', 'PROF_SEC', 'COD_REG', 'VARIABLE', 'VALOR'],
      dtype='object')

In [21]:
# Unimos todos los dataframes en uno solo 

df_fisico_quimico_2019 = pd.concat([df_fisio_2019 , df_fisio_maullin_copy ,  df_termistor_final])

# Modificamos el NOMB_PROY 

df_fisico_quimico_2019['NOMB_PROY'] = 'ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICULTURA EN CHILE Y SU EFECTO EN LOS ECOSISTEMAS DE EMPLAZAMIENTO 2019-2020'

# Agregamos el SECTOR

df_fisico_quimico_2019['SECTOR'] = 'Maullín'

# Convertimos la columna ESTACION a string y luego eliminamos los .

# 1) A string (respetando NaN)
df_fisico_quimico_2019['ESTACION'] = df_fisico_quimico_2019['ESTACION'].astype('string')

# 2) Tomar lo anterior al primer '.'
df_fisico_quimico_2019['ESTACION'] = df_fisico_quimico_2019['ESTACION'].str.split('.', n=1).str[0]

# 3) Convertir a entero anulable (conserva NaN)
df_fisico_quimico_2019['ESTACION'] = pd.to_numeric(df_fisico_quimico_2019['ESTACION'], errors='coerce').astype('Int64')

# Convertimos la columna de PROF_SEC

df_fisico_quimico_2019['PROF_SEC'] = df_fisico_quimico_2019['PROF_SEC'].astype(float)

In [43]:
df_fisico_quimico_2019.query('ID == 4 and VALOR.notna()')

,ID,NOMB_PROY,COD_PROY,FECHA_INI,FECHA_TER,LATITUD,LONGITUD,ESTACION,PROF_SEC,COD_REG,EQUIPO,VARIABLE,VALOR,SECTOR
3,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,05/12/2019 00:00:00,05/12/2019 00:00:00,-41.59125,-73.630472,4,1.2,X,Orion 4-Star pH/ISE,PROF_EQUIPO,0.01,Maullín
243,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,05/12/2019 00:00:00,05/12/2019 00:00:00,-41.59125,-73.630472,4,1.2,X,Orion 4-Star pH/ISE,TEMPERATURA,18.7,Maullín
483,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,05/12/2019 00:00:00,05/12/2019 00:00:00,-41.59125,-73.630472,4,1.2,X,Orion 4-Star pH/ISE,PH,8.4,Maullín
771,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,05/12/2019 00:00:00,05/12/2019 00:00:00,-41.59125,-73.630472,4,1.2,X,Refractometro,PROF_EQUIPO,0.01,Maullín
1011,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,05/12/2019 00:00:00,05/12/2019 00:00:00,-41.59125,-73.630472,4,1.2,X,Refractometro,SALINIDAD,2.1,Maullín
1299,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,05/12/2019 00:00:00,05/12/2019 00:00:00,-41.59125,-73.630472,4,1.2,X,Mini DO2T Logger (PME),PROF_EQUIPO,1.2,Maullín
1827,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,05/12/2019 00:00:00,05/12/2019 00:00:00,-41.59125,-73.630472,4,1.2,X,Disco Sechi,PROF_EQUIPO,1.2,Maullín
2067,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,05/12/2019 00:00:00,05/12/2019 00:00:00,-41.59125,-73.630472,4,1.2,X,Disco Sechi,TRANSPARENCIA,1,Maullín
2355,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,05/12/2019 00:00:00,05/12/2019 00:00:00,-41.59125,-73.630472,4,1.2,X,Onset HOBO UA-002-64 Pendant 64K,PROF_EQUIPO,1.2,Maullín
2595,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,05/12/2019 00:00:00,05/12/2019 00:00:00,-41.59125,-73.630472,4,1.2,X,Onset HOBO UA-002-64 Pendant 64K,LUZ_PAR,176.29945,Maullín
2835,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,05/12/2019 00:00:00,05/12/2019 00:00:00,-41.59125,-73.630472,4,1.2,X,Onset HOBO UA-002-64 Pendant 64K,CLOROFILA_A,4.237362,Maullín
3075,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,05/12/2019 00:00:00,05/12/2019 00:00:00,-41.59125,-73.630472,4,1.2,X,Onset HOBO UA-002-64 Pendant 64K,CLOROFILA_ACT,1.971736,Maullín
3315,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,05/12/2019 00:00:00,05/12/2019 00:00:00,-41.59125,-73.630472,4,1.2,X,Onset HOBO UA-002-64 Pendant 64K,FEOPIGM,2.265626,Maullín
3555,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,05/12/2019 00:00:00,05/12/2019 00:00:00,-41.59125,-73.630472,4,1.2,X,Onset HOBO UA-002-64 Pendant 64K,FEOPIGM_%,53.467841,Maullín
3795,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,05/12/2019 00:00:00,05/12/2019 00:00:00,-41.59125,-73.630472,4,1.2,X,Onset HOBO UA-002-64 Pendant 64K,MATERIA INORGANICA,0.012262,Maullín
4035,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,05/12/2019 00:00:00,05/12/2019 00:00:00,-41.59125,-73.630472,4,1.2,X,Onset HOBO UA-002-64 Pendant 64K,MATERIA ORGANICA,0.003095,Maullín
4275,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,05/12/2019 00:00:00,05/12/2019 00:00:00,-41.59125,-73.630472,4,1.2,X,Onset HOBO UA-002-64 Pendant 64K,NITRATO,0.702,Maullín
4515,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,05/12/2019 00:00:00,05/12/2019 00:00:00,-41.59125,-73.630472,4,1.2,X,Onset HOBO UA-002-64 Pendant 64K,FOSFATO,0.312,Maullín
4755,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,05/12/2019 00:00:00,05/12/2019 00:00:00,-41.59125,-73.630472,4,1.2,X,Onset HOBO UA-002-64 Pendant 64K,SILICATO,35.07,Maullín
3,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,05/12/2019 00:00:00,05/12/2019 00:00:00,-41.59125,-73.630472,4,NaN,X,Buceo autonomo,BIO_PEL_R1,4.304,Maullín
51,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,05/12/2019 00:00:00,05/12/2019 00:00:00,-41.59125,-73.630472,4,NaN,X,Buceo autonomo,BIO_PEL_R2,3.024,Maullín
99,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,05/12/2019 00:00:00,05/12/2019 00:00:00,-41.59125,-73.630472,4,NaN,X,Buceo autonomo,BIO_PEL_R3,4.18,Maullín
147,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,05/12/2019 00:00:00,05/12/2019 00:00:00,-41.59125,-73.630472,4,NaN,X,Buceo autonomo,BIO_VER_R1,0,Maullín
195,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,05/12/2019 00:00:00,05/12/2019 00:00:00,-41.59125,-73.630472,4,NaN,X,Buceo autonomo,BIO_VER_R2,0,Maullín
243,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,05/12/2019 00:00:00,05/12/2019 00:00:00,-41.59125,-73.630472,4,NaN,X,Buceo autonomo,BIO_VER_R3,0,Maullín
291,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,05/12/2019 00:00:00,05/12/2019 00:00:00,-41.59125,-73.630472,4,NaN,X,Buceo autonomo,BIO_TOT_R1,4.304,Maullín
339,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,05/12/2019 00:00:00,05/12/2019 00:00:00,-41.59125,-73.630472,4,NaN,X,Buceo autonomo,BIO_TOT_R2,3.024,Maullín
387,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,05/12/2019 00:00:00,05/12/2019 00:00:00,-41.59125,-73.630472,4,NaN,X,Buceo autonomo,BIO_TOT_R3,4.18,Maullín
435,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,05/12/2019 00:00:00,05/12/2019 00:00:00,-41.59125,-73.630472,4,NaN,X,Buceo autonomo,COB_PEL_R1,100,Maullín
483,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,05/12/2019 00:00:00,05/12/2019 00:00:00,-41.59125,-73.630472,4,NaN,X,Buceo autonomo,COB_PEL_R2,100.0,Maullín
531,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,05/12/2019 00:00:00,05/12/2019 00:00:00,-41.59125,-73.630472,4,NaN,X,Buceo autonomo,COB_PEL_R3,100,Maullín
579,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,05/12/2019 00:00:00,05/12/2019 00:00:00,-41.59125,-73.630472,4,NaN,X,Buceo autonomo,COB_VER_R1,0,Maullín
627,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,05/12/2019 00:00:00,05/12/2019 00:00:00,-41.59125,-73.630472,4,NaN,X,Buceo autonomo,COB_VER_R2,0,Maullín
675,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,05/12/2019 00:00:00,05/12/2019 00:00:00,-41.59125,-73.630472,4,NaN,X,Buceo autonomo,COB_VER_R3,0,Maullín
3841,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,05/12/2019 00:00:00,05/12/2019 18:26:00,-41.586083,-73.646333,<NA>,NaN,X,Thermochron DS1921H,TEMPERATURA,19.375,Maullín
699,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,14/04/2020 00:00:00,14/04/2020 17:47:00,-41.591028,-73.642111,<NA>,NaN,X,Thermochron DS1921H,TEMPERATURA,13,Maullín
3841,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,12/02/2020 00:00:00,12/02/2020 17:42:00,-41.599389,-73.619222,<NA>,NaN,X,Thermochron DS1921H,TEMPERATURA,15.25,Maullín

In [180]:
# Convertimos la columna de ESTACION a entero

df_fisico_quimico_2019.to_csv('output/2019/AMBIENTALES_FISICO_QUIMICOS_2019.csv' , index=False)

In [183]:

# Si hay strings, símbolos o espacios, primero normaliza:
df_fisico_quimico_2019['ESTACION'] = pd.to_numeric(df_fisico_quimico_2019['ESTACION'], errors='coerce')

In [187]:
df_fisico_quimico_2019['ESTACION'].unique()

array([ 1.,  2.,  3.,  4.,  5., nan])

# Limpieza de Fisico Quimicos 2019 - Nueva Version

In [39]:
df_fisico = pd.read_excel(r'C:\Users\felipe.abarzua\Desktop\workspace\DATA_AMBIENTALES\Proyecto Seguimiento Ambiental\FISICO QUIMICOS_2012-2024\1_BD_FISICOQUIMICO_2019.xlsx')

In [41]:
df_fisico

,Nombre del Proyecto:,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICULTURA EN CHILE Y SU EFECTO EN LOS ECOSISTEMAS DE EMPLAZAMIENTO 2019-2020,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,Etapa Proyecto:,Objetivo 1. Actividad 2. Muestreos y Analisis ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Jefe Proyecto,Gastón Vidal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Institucion:,INSTITUTO DE FOMENTO PESQUERO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Nombre Sector:,"Atacama (Caldera-Bahia Inglesa), Coquimbo (Ton...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Región:,"Región de Atacama, Región de Coquimbo, Región ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180,ESTUDIO DEL DESEMPEÑO AMBIENTAL DE LA ACUICULT...,Objetivo 1. Actividad 2. Muestreos y Analisis ...,Gastón Vidal,INSTITUTO DE FOMENTO PESQUERO,Campaña_Inv_Ver_2019.Proy.SeguimientoAmbiental,Valdivia,4,"39°51'53,8''","73°21'38,8''",7.176667,...,407.666667,33.838046,0.0,0.0,0.977428,1.5,s/i,2019-07-26 00:00:00,s/i,4
181,ESTUDIO DEL DESEMPEÑO AMBIENTAL DE LA ACUICULT...,Objetivo 1. Actividad 2. Muestreos y Analisis ...,Gastón Vidal,INSTITUTO DE FOMENTO PESQUERO,Campaña_Inv_Ver_2019.Proy.SeguimientoAmbiental,Valdivia,6,"39°52'46,5''","73°22'53,5''",7.543333,...,376.6,13.291727,0.0,0.0,1.309219,2.5,s/i,2019-07-26 00:00:00,s/i,6
182,ESTUDIO DEL DESEMPEÑO AMBIENTAL DE LA ACUICULT...,Objetivo 1. Actividad 2. Muestreos y Analisis ...,Gastón Vidal,INSTITUTO DE FOMENTO PESQUERO,Campaña_Inv_Ver_2019.Proy.SeguimientoAmbiental,Valdivia,9,"39°53'36,9''","73°21'46,5''",7.55,...,97.833333,20.886918,75.684237,48.737273,11.553874,2.5,s/i,2019-07-26 00:00:00,s/i,9
183,ESTUDIO DEL DESEMPEÑO AMBIENTAL DE LA ACUICULT...,Objetivo 1. Actividad 2. Muestreos y Analisis ...,Gastón Vidal,INSTITUTO DE FOMENTO PESQUERO,Campaña_Inv_Ver_2019.Proy.SeguimientoAmbiental,Valdivia,11,"39°53'35,9''","73°22'19,4''",7.48,...,180.6,16.89349,76.939347,53.757601,11.061239,1.5,s/i,2019-07-26 00:00:00,s/i,11
184,ESTUDIO DEL DESEMPEÑO AMBIENTAL DE LA ACUICULT...,Objetivo 1. Actividad 2. Muestreos y Analisis ...,Gastón Vidal,INSTITUTO DE FOMENTO PESQUERO,Campaña_Inv_Ver_2019.Proy.SeguimientoAmbiental,Valdivia,15,"39°55'47,5''","73°23'41,2''",7.616667,...,125.6,35.096296,8.533643,2.848958,10.240249,1.5,s/i,2019-07-26 00:00:00,s/i,15

In [60]:
def limpieza_fisicoquimico(df):

    # Realizamos una copia del dataset
    df_fisico_copy = df.copy()

    # Eliminamos las filas innecesarias
    df_fisico_copy = df_fisico_copy.iloc[14: , :]

    # Dejamos la primera fila como columnas 
    df_fisico_copy.columns = df_fisico_copy.iloc[0]

    # Eliminamos la primera fila 
    df_fisico_copy = df_fisico_copy.iloc[1: , :]

    #Reiniciamos los indices
    df_fisico_copy = df_fisico_copy.reset_index(drop=True)

    #Seleccionamos las columnas
    df_fisico_copy = df_fisico_copy[['NOMB_PROY', 'ETAP_PROY', 'JEFE_PROY', 'INST_PROY', 'CAMPAÑA', 'ZONA',
       'ESTACION', 'Latitud S                ' , 'Longitud W ', 'pH' , 'Temperatura (°C)' , 'Redox EHNHE (mV)' , 'Sulfuros (µM)   ' , 'Materia orgánica total (%)',
        'Fecha',
       'Hora Muestreo' ]]

    # Agregamos la columna ID

    df_fisico_copy.insert(0 , 'ID' , df_fisico_copy.index + 1 )

    # Creamos una lista de columnas 

    lista_columnas = df_fisico_copy.columns.to_list()


    # Creamos una funcion para eliminar todo el contenido que esta en parentesis (*)

    def es_nan(x):
        return isinstance(x, float) and math.isnan(x)


    def quitar_parentesis_contenido(lista):
    
        resultado = []
        patron = re.compile(r'\([^)]*\)')  # todo lo que esté entre paréntesis (no anida)
        for c in lista:
            if es_nan(c) or c is None:
                resultado.append(c)
            elif isinstance(c, str):
                s = patron.sub('', c)                 # quita ( ... )
                s = re.sub(r'\s{2,}', ' ', s).strip() # colapsa espacios y recorta
                resultado.append(s)
            else:
                resultado.append(c)
        return resultado

    # Aplicamos la funcion para limpiar las columnas 
    lista_columnas = quitar_parentesis_contenido(lista_columnas)

    # Cambiamos las columnas del dataset

    df_fisico_copy.columns = lista_columnas

    # Creamos las columnas fijas y columnas variables

    indices_fijos = [0 , 1 , 2 ,3 ,4 ,5 ,6 ,7 , 8 , 9 ,  15 , 16]

    columnas_fijas = [lista_columnas[i] for i in indices_fijos]

    columnas_variables = [col for i, col in enumerate(lista_columnas) if i not in indices_fijos]

    
    # Ahora realizamos un melt para convertir las columnas variables en filas

    df_fisico_copy = pd.melt(df_fisico_copy , id_vars= columnas_fijas , value_vars= columnas_variables , var_name= 'VARIABLE' , value_name='VALOR' )

    # Convertimos la columna de VARIABLE a mayuscula

    df_fisico_copy['VARIABLE'] = df_fisico_copy['VARIABLE'].str.upper()

    #Corregimos los variables 's/d'
    df_fisico_copy['VALOR'] = np.where(df_fisico_copy['VALOR'] == 'SIN DATO', np.nan , df_fisico_copy['VALOR'] )
    df_fisico_copy['VALOR'] = np.where(df_fisico_copy['VALOR'] == 'sd', np.nan , df_fisico_copy['VALOR'] )
    df_fisico_copy['VALOR'] = np.where(df_fisico_copy['VALOR'] == 's/d', np.nan , df_fisico_copy['VALOR'] )
    
    #Eliminamos las filas con VALOR no nulo 

    df_fisico_copy = df_fisico_copy[df_fisico_copy['VALOR'].notnull()]

    #Reiniciamos los indices    
    df_fisico_copy = df_fisico_copy.reset_index(drop = True)

    # Cambiamos el tipo de dato de la columna Fecha 

    df_fisico_copy['Fecha'] = pd.to_datetime(df_fisico_copy['Fecha'], errors='coerce')

    #Creamos una columna para unir la Fecha y Hora Muestreo

    # Convertimos las Hora_Muestreo que son invalidos a 00:00:00
    df_fisico_copy['Hora Muestreo'] = np.where(df_fisico_copy['Hora Muestreo'] == 'sd' , datetime.time(0,0) , df_fisico_copy['Hora Muestreo'])
    df_fisico_copy['Hora Muestreo'] = np.where(df_fisico_copy['Hora Muestreo'] == 's/i' , datetime.time(0,0) , df_fisico_copy['Hora Muestreo'])


    #Creamos la columna llamada FECHA_MUESTREO que combine la fecha y la hora de muestreo
    df_fisico_copy['FECHA_MUESTREO'] = df_fisico_copy['Fecha'].dt.strftime('%d/%m/%Y') + " " + df_fisico_copy['Hora Muestreo'].astype(str)

    # Convertimos las variables 
    df_fisico_copy['VARIABLE'] = np.where(df_fisico_copy['VARIABLE'] == 'MATERIA ORGÁNICA TOTAL' , 'MATERIA ORGANICA' , df_fisico_copy['VARIABLE'])


    def normalizar(s):
            if pd.isna(s):
                return s
            # quitar tildes, bajar a minúsculas y recortar espacios
            s = ''.join(c for c in unicodedata.normalize('NFD', str(s).strip().lower())
                        if unicodedata.category(c) != 'Mn')
            return s

    # Agregamos la columna de COD_REGION
    
    # Diccionario en números romanos
        
    mapa_romano = {
            # Los Lagos (X)
            'reloncavi': 'X',
            'estuario': 'X',
            'calbuco': 'X',
            'maullin': 'X',
            'ancud': 'X',
            'chacao': 'X',
            'butachauques': 'X',
            'chaulinec': 'X',
            'tenaun': 'X',
            'chiloe central': 'X',
            'desertores': 'X',
            'quellon': 'X',
            'hornopiren': 'X',
            'ayacara': 'X',
            'chaiten': 'X',

            # Aysén (XI)
            'guaitecas': 'XI',
            'moraleda': 'XI',
            'puyuhuapi': 'XI',
            'aysen': 'XI',

            # Coquimbo (IV)
            'coquimbo': 'IV',
            'tongoy': 'IV',

            # Atacama (III)
            'atacama': 'III',

            # Magallanes (Natales) – XII
            'natales': 'XII',

            # Biobío (VIII)
            'bio-bio': 'VIII',

            # Los Ríos (XIV)
            'valdivia': 'XIV',
        }

    # Aplicamos la funcion para obtener el COD_REGION
    df_fisico_copy['COD_REGION'] = df_fisico_copy['ZONA'].apply(normalizar).map(mapa_romano)

    #Aplicamos una funcion para eliminar las ' y ° de LATITUD Y LONGITUD 

    df_fisico_copy['Longitud W'] = df_fisico_copy['Longitud W'].str.replace(r"[°'\"]", "", regex=True).str.rstrip().str.replace(',' , '.')
    df_fisico_copy['Latitud S'] = df_fisico_copy['Latitud S'].str.replace(r"[°'\"]", "", regex=True).str.rstrip().str.replace(',' , '.')

    #Renombramos el Proyecto

    df_fisico_copy['NOMB_PROY'] = 'ESTUDIO DEL DESEMPEÑO AMBIENTAL DE LA ACUICULTURA EN CHILE Y SU EFECTO EN LOS ECOSISTEMAS DE EMPLAZAMIENTO 2019-2020'

    #Renombramos los dataframes

    df_fisico_copy = df_fisico_copy.rename(columns={'Longitud W' : 'LONGITUD' , 'Latitud S' : 'LATITUD'})

    return df_fisico_copy , lista_columnas

In [62]:

df_fisico_copy , lista_columnas = limpieza_fisicoquimico(df_fisico)

In [64]:
df_fisico_copy.columns

Index(['ID', 'NOMB_PROY', 'ETAP_PROY', 'JEFE_PROY', 'INST_PROY', 'CAMPAÑA',
       'ZONA', 'ESTACION', 'LATITUD', 'LONGITUD', 'Fecha', 'Hora Muestreo',
       'VARIABLE', 'VALOR', 'FECHA_MUESTREO', 'COD_REGION'],
      dtype='object')

In [68]:
df_fisico_copy['FECHA_MUESTREO'].unique()

array(['10/05/2019 15:55:00', '10/05/2019 16:40:00',
       '10/05/2019 14:55:00', '10/05/2019 12:55:00',
       '10/05/2019 11:18:00', '10/05/2019 12:20:00',
       '10/05/2019 10:25:00', '10/05/2019 09:55:00',
       '10/05/2019 09:02:00', '10/05/2019 08:15:00',
       '12/05/2019 15:40:00', '12/05/2019 00:00:00',
       '30/05/2019 11:00:00', '09/05/2019 00:00:00',
       '12/05/2019 14:30:00', '30/05/2019 00:00:00',
       '30/05/2019 13:15:00', '02/06/2019 00:00:00',
       '30/05/2019 15:00:00', '30/05/2019 16:20:00',
       '02/06/2019 16:46:00', '02/06/2019 16:00:00',
       '02/06/2019 15:18:00', '06/06/2019 00:00:00',
       '03/06/2019 00:00:00', '03/06/2019 09:20:00',
       '03/06/2019 08:35:00', '08/06/2019 08:11:00',
       '08/06/2019 08:45:00', '06/06/2019 17:26:00',
       '06/06/2019 17:00:00', '07/06/2019 13:42:00',
       '07/06/2019 12:22:00', '07/06/2019 00:00:00',
       '07/06/2019 11:00:00', '07/06/2019 16:00:00',
       '07/06/2019 17:56:00', '15/05/2019 00:00:00',
       '09/06/2019 16:56:00', '09/06/2019 17:49:00',
       '09/06/2019 18:24:00', '09/06/2019 16:02:00',
       '09/06/2019 15:10:00', '09/06/2019 13:09:00',
       '09/06/2019 12:40:00', '09/06/2019 11:59:00',
       '09/06/2019 11:00:00', '09/06/2019 09:09:00',
       '09/06/2019 10:10:00', '08/06/2019 14:10:00',
       '13/05/2019 00:00:00', '14/05/2019 00:00:00',
       '16/05/2019 00:00:00', '20/05/2019 00:00:00',
       '19/05/2019 00:00:00', '18/05/2019 00:00:00',
       '14/06/2019 15:12:00', '14/06/2019 13:40:00',
       '14/06/2019 11:34:00', '14/06/2019 10:10:00',
       '14/06/2019 08:50:00', '13/06/2019 09:54:00',
       '13/06/2019 08:55:00', '13/06/2019 10:53:00',
       '13/06/2019 00:00:00', '13/06/2019 15:50:00',
       '15/06/2019 17:17:00', '15/06/2019 16:20:00',
       '15/06/2019 14:55:00', '15/06/2019 09:55:00',
       '15/06/2019 09:00:00', '14/06/2019 17:22:00',
       '14/06/2019 16:20:00', '13/06/2019 14:00:00',
       '25/06/2019 16:02:00', '24/06/2019 10:30:00',
       '25/06/2019 11:45:00', '25/06/2019 09:06:00',
       '25/06/2019 08:25:00', '24/06/2019 15:17:00',
       '24/06/2019 14:05:00', '18/06/2019 10:38:00',
       '18/06/2019 13:15:00', '17/06/2019 15:52:00',
       '17/06/2019 11:55:00', '17/06/2019 08:55:00',
       '19/06/2019 14:50:00', '19/06/2019 15:39:00',
       '20/06/2019 08:44:00', '21/06/2019 14:01:00',
       '21/06/2019 15:00:00', '16/06/2019 15:20:00',
       '16/06/2019 13:30:00', '16/06/2019 11:55:00',
       '16/06/2019 10:20:00', '23/06/2019 11:00:00',
       '15/04/2019 00:00:00', '11/04/2019 00:00:00',
       '10/08/2019 15:24:00', '10/08/2019 16:19:00',
       '11/08/2019 22:45:00', '11/08/2019 12:49:00',
       '11/08/2019 15:43:00', '11/08/2019 17:58:00',
       '11/08/2019 18:40:00', '11/08/2019 10:16:00',
       '24/07/2019 00:00:00', '26/07/2019 00:00:00'], dtype=object)

In [67]:
df_fisico_copy.shape

(835, 16)

In [69]:

df_fisico_copy.to_csv('output/2019/AMBIENTALES_FISICOQUIMICO_2019.csv' , index=False)

# Limpieza CTD Nueva Versión

In [2]:
df_ctd_new = pd.read_excel(r'C:\Users\felipe.abarzua\Desktop\workspace\DATA_AMBIENTALES\Proyecto Seguimiento Ambiental\CTD_2019-2024\1_BD_CTD_SEGUIMIENTO_2019.xlsx')

In [3]:
df_ctd_new

,Nombre del Proyecto:,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICULTURA EN CHILE Y SU EFECTO EN LOS ECOSISTEMAS DE EMPLAZAMIENTO 2019 -2020,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27
0,Codigo del Proyecto:,656-115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Fecha inicio del muestreo:,9 mayo de 2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Fecha fin del muestreo:,26 de junio 2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Equipos de medición:,CTD SeaBird SBE19plus// SerialNumber 01907566/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Botella Niskin 5 litros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-06-20 00:00:00,2019-06-20 00:00:00,CTD SeaBird SBE19plus,-46.676652,-73.9255,127,135.9,6.1698,...,NaN,NaN,NaN,NaN,XI,31,31,LAGUNA SAN RAFAEL,14:56:00,NaN
6429,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-06-20 00:00:00,2019-06-20 00:00:00,CTD SeaBird SBE19plus,-46.676652,-73.9255,128,135.9,6.1781,...,NaN,NaN,NaN,NaN,XI,31,31,LAGUNA SAN RAFAEL,14:56:00,NaN
6430,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-06-20 00:00:00,2019-06-20 00:00:00,CTD SeaBird SBE19plus,-46.676652,-73.9255,129,135.9,6.1842,...,NaN,NaN,NaN,NaN,XI,31,31,LAGUNA SAN RAFAEL,14:56:00,NaN
6431,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-06-20 00:00:00,2019-06-20 00:00:00,CTD SeaBird SBE19plus,-46.676652,-73.9255,130,135.9,6.1917,...,NaN,NaN,NaN,NaN,XI,31,31,LAGUNA SAN RAFAEL,14:56:00,NaN
6432,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-115,2019-06-20 00:00:00,2019-06-20 00:00:00,CTD SeaBird SBE19plus,-46.676652,-73.9255,131,135.9,6.1961,...,NaN,NaN,NaN,NaN,XI,31,31,LAGUNA SAN RAFAEL,14:56:00,NaN

In [32]:
def limpieza_ctd_2019(df):

    # Creamos una copia del dataset
    df_ctd_copy = df.copy()

    # Eliminamos las filas innecesarias
    df_ctd_copy = df_ctd_copy.iloc[18:  , : ]

    # Dejamos la primera fila como columnas
    df_ctd_copy.columns = df_ctd_copy.iloc[0]

    # Eliminamos la primera fila 
    df_ctd_copy = df_ctd_copy.iloc[1: , :]

    #Reiniciamos los indices
    df_ctd_copy = df_ctd_copy.reset_index(drop = True)

    #Agregamos la columna ID 
    df_ctd_copy.insert(0 , 'ID' , df_ctd_copy.index + 1)


    #Creamos la lista de columnas 
    columnas = df_ctd_copy.columns.to_list()
    
    #Creamos las columnas fijas y variables

    columnas_fijas = ['ID', 'NOMB_PROY', 'COD_PROY', 'FECHA_INI', 'FECHA_TER', 'EQUIPO', 'LATITUD', 'LONGUITUD', 'ESTACION', 'PROF_EQ', 'PROF_SECT' , 'HORA_DATO  ' , 'COD_REG' , 'SECTOR']
    
    columnas_variables = [c for c in df_ctd_copy.columns if c not in columnas_fijas]

    df_ctd_copy['HORA_DATO  '] = df_ctd_copy['HORA_DATO  '].fillna(datetime.time(0, 0))
    
    #Realizamos un melt para convertir las columnas_variables en filas 
    df_ctd_copy = pd.melt(df_ctd_copy , id_vars= columnas_fijas , value_vars= columnas_variables , var_name= 'VARIABLE' , value_name='VALOR')

        #Vamos a reemplazar los valores e HORA_INICIO ya que están mal escritos

    def normalizar_hora_string(hora_str):

            #Normaliza una cadena de tiempo para asegurar que los minutos tengan dos dígitos.
            #Ej: '12:5' se convierte en '12:05'.
            
        if pd.isna(hora_str): # Maneja posibles valores NaN/nulos si los hubiera
            return hora_str

        partes = str(hora_str).split(':')
        if len(partes) != 2:
                # Manejar casos donde el formato no es 'HH:MM' (ej. ya está mal, o es un dato inesperado)
                # Puedes decidir si quieres levantar un error, devolver el original, o un valor específico.
                # Por simplicidad, devolveremos el original si el formato no es el esperado de dos partes.
            return hora_str

        horas = partes[0]
        minutos = partes[1]

        if len(minutos) == 1:
            minutos = '0' + minutos # Añadir el cero delante si es un solo dígito

            return f"{horas}:{minutos}"
        
     #Aplicamos la funcion de hora a la columnas HORA_INICIO
    df_ctd_copy['HORA_DATO  '] = df_ctd_copy['HORA_DATO  '].apply(normalizar_hora_string)

        # Creamos una funcion para convertir la columna de HORA_INICIO a datetime para luego Crear una columna de fecha y hora 
    def convertir_hora(time_value):
        if isinstance(time_value, str): 
            # Separamos el ":" del texto y lo convertimos a entero y obtenemos dos variables
            horas, minutos = map(int, time_value.split(':'))
            #Retornamos los valores de Horas y minutos
            return datetime.time(horas, minutos)
        else:
            # En caso que ya es datetime.time se deja como esta
            return time_value


    df_ctd_copy['HORA_DATO  '] = df_ctd_copy['HORA_DATO  '].apply(convertir_hora)


    #Cambiamos los tipos de FECHA_INI y FECHA_FIN a datetime

    df_ctd_copy['FECHA_INI'] = pd.to_datetime(df_ctd_copy['FECHA_INI'])
    df_ctd_copy['FECHA_TER'] = pd.to_datetime(df_ctd_copy['FECHA_TER'])

        #FECHA INI CONVERTIDA A STRING 
    df_ctd_copy['FECHA_INI_STR'] =  df_ctd_copy['FECHA_INI'].dt.strftime("%d/%m/%Y")
    df_ctd_copy['FECHA_TERMINO'] = df_ctd_copy['FECHA_TER'].dt.strftime("%d/%m/%Y")

        
        #Creamos una funcion lambda para combinar FECHA_INI con la HORA_INI
    df_ctd_copy['FECHA_INICIO'] = df_ctd_copy.apply(
        lambda row: datetime.datetime.strptime(row['FECHA_INI_STR'], "%d/%m/%Y").replace(
            hour=row['HORA_DATO  '].hour,
            minute=row['HORA_DATO  '].minute,
            second=row['HORA_DATO  '].second
            ),
            axis=1
        )

        # Modificamos el formato de FECHA_INICIO 
    df_ctd_copy['FECHA_INICIO'] = df_ctd_copy['FECHA_INICIO'].dt.strftime("%d/%m/%Y %H:%M:%S")

    # Eliminamos las columnas innecesarias
    df_ctd_copy = df_ctd_copy[['ID', 'NOMB_PROY', 'COD_PROY', 'EQUIPO','LATITUD', 'LONGUITUD', 'ESTACION', 'PROF_EQ', 'PROF_SECT', 'COD_REG', 'SECTOR', 'VARIABLE', 'VALOR',
                                'FECHA_TERMINO', 'FECHA_INICIO']]

    # Cambiamos las variables
    df_ctd_copy['VARIABLE'] = np.where(df_ctd_copy['VARIABLE'] == 'DISCO_SECH' , 'DISCO SECCHI' , df_ctd_copy['VARIABLE'] )
    df_ctd_copy['VARIABLE'] = np.where(df_ctd_copy['VARIABLE'] == 'TEMPERATUR' , 'TEMPERATURA' , df_ctd_copy['VARIABLE'] )
    df_ctd_copy['VARIABLE'] = np.where(df_ctd_copy['VARIABLE'] == 'FLUORESCEN' , 'FLUORESCENCIA' , df_ctd_copy['VARIABLE'] )
   
    #Limpiamos los Sectores
    df_ctd_copy['SECTOR'] = df_ctd_copy['SECTOR'].str.rstrip()

    # Cambiamos el nombre del proyecto
    df_ctd_copy['NOMB_PROY'] = 'ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICULTURA EN CHILE Y SU EFECTO EN LOS ECOSISTEMAS DE EMPLAZAMIENTO 2019-2020'

    # Dejamos las variable en mayuscula
    df_ctd_copy['VARIABLE'] = df_ctd_copy['VARIABLE'].str.upper()

    # Reemplazamos los valores de sd , '˂ L.D.'
    df_ctd_copy['VALOR'] = np.where(df_ctd_copy['VALOR'] == 'sd' , np.nan , df_ctd_copy['VALOR'])
    df_ctd_copy['VALOR'] = np.where(df_ctd_copy['VALOR'] == '˂ L.D.' , np.nan , df_ctd_copy['VALOR'])

    return df_ctd_copy , columnas

In [28]:
df_ctd_new_copy , columnas = limpieza_ctd_2019(df_ctd_new)

In [29]:
df_ctd_new_copy.columns

Index(['ID', 'NOMB_PROY', 'COD_PROY', 'EQUIPO', 'LATITUD', 'LONGUITUD',
       'ESTACION', 'PROF_EQ', 'PROF_SECT', 'COD_REG', 'SECTOR', 'VARIABLE',
       'VALOR', 'FECHA_TERMINO', 'FECHA_INICIO'],
      dtype='object')

In [34]:
df_ctd_new_copy['VALOR'].unique()

array([12.2883, 12.0498, 11.7416, ..., 30, 0.5, 6.5], dtype=object)

In [35]:
df_ctd_new_copy.to_csv('output/2019/AMBIETNALES_CTD_2019_V2.csv' , index= False)